[quote.epigraph, , 1 Thess. 5:21]
____
Prove all things, hold fast that which is good.
____

[#reasons, short="A Few Reasons for Leaving"]
== A Few Reasons for Leaving the National Established Mode of Worship

The following is a compilation of three letters written
by John Spalding the year prior his death,
in the 29th year of age,
addressed to beloved friends and fellow professors of
Christianity who were then attending Saint Giles Church,
in Reading.

[.asterism]
'''

Friends, my mind has been much exercised at times, since I separated from your communion,
with desires for your real advancement in the spirit
and power of that religion you make profession of.
And being persuaded there are those among you who do really desire to know the truth,
I feel a renewed concern to salute you, in a degree, I hope, of true gospel love;
and to offer to your serious consideration the reasons
which induced me to separate from your society.
And truly, friends, there were many ties which nearly united me to you;
and I was very unwilling for a considerable time to
believe that those things I had been engaged in,
and so highly esteemed, were not what they had appeared to be.
But, as I earnestly desired to know the truth, whatever it might cost me,
I felt the axe laid to the root of the tree,
and the fine buildings and plausible appearances were shaken.
I became sensible, that the tree must first be made good before the fruit could be good;
a doctrine essentially different from what I had heard of men,
even of men highly esteemed.
For I was taught that deliverance from sin is not to be expected in this life,
and was hearing day after day the uniform acknowledgement that we are
"`miserable sinners, having no spiritual health,`" etc.
This I found,
by the manifestations of that Spirit which "`is given to every man to profit withal,`"^
footnote:[1 Corinthians 12:7]
and which discovers the secret things of darkness, to be not agreeable,
but indeed contrary, to the Scriptures of truth.
For these expressly declare,
that the great Author of the gospel dispensation
"`came to save His people from their sins,`"^
footnote:[Matthew 1:21]
and not in them--a very essential difference.
This I saw must be experientially known, feeling sin to be the great disease of the soul,
the sole cause of separation from the Most High, in whom alone true happiness is found.
I was sensible that while sin remained, the separation must continue,
there being "`no communion between light and darkness, righteousness and unrighteousness;`"^
footnote:[2 Corinthains 6:14]
nor could that gracious promise be fulfilled,
"`I will dwell in them, and walk in them, I will be their God, and they shall be My people;`"^
footnote:[2 Corinthians 6:16;]
for the apostle says, "`You are the temple of God, and the temple of God is holy.`"^
footnote:[1 Corinthians 3:17.]

What is a true Christian?
Is it one who assents to and believes certain facts, as recorded in holy writ,
and forms certain principles and opinions thereupon;
producing perhaps a partial reformation,
an abstaining from the grosser pollutions of sin,
but denying the possibility of a total cleansing and freedom from sin in this world?
Or is it one who knows not in word only, but in deed and in truth, a death unto sin,
and a new birth unto righteousness; a being born again, not of blood,
nor of the will of the flesh, nor of man, but of God?
"`For,`" says our blessed Lord,
"`except a man be born again, he cannot enter into the kingdom of God.`"^
footnote:[John 3:3]
A man may know with Nicodemus, and freely confess,
that Christ is a teacher sent from God;
he may be able to talk much about the doctrines of the gospel,
and fancy himself secure by imputation,
but what has this to do with the new birth which is so fundamentally necessary?
What can all his wisdom and understanding teach him?
No, man cannot come into the new birth till all is parted with,
for the very nature of the thing implies a beginning again,
a life as essentially different from his former as light is from darkness.
"`You were formerly darkness,`" says Paul, "`but now are you are light in the Lord.`"^
footnote:[Ephesians 5:8]
Now he who knows this new birth--not a change of opinion,
not a comprehending the truths of the gospel in his understanding,
or a joining to this or that society--but who knows the thing itself--not the name,
nor imaginations concerning it, but the nature, the life,
the essence--will such a man remain what he was before?

Christ said, "`Blessed are the pure in heart;`"^
footnote:[Matthew 5:8]
but modern Christians say, "`There is no purity of heart,
but it is and must remain deceitful above all things and desperately wicked.`"
Again it is said, "`Who brings a clean thing out of an unclean?`"^
footnote:[Job 14:4]
Now, that the heart is naturally unclean is granted,
but has not the Lord promised to cleanse His people from "`all their uncleanness?`"
Mark the word "`all;`" what uncleanness will then remain?
Some attempt to excuse themselves by what Paul once experienced;
"`The flesh lusts against the Spirit, and the Spirit against the flesh;`"^
footnote:[Galatians 5:17]
or "`a law in the members warring against the law of the mind.`"^
footnote:[Romans 7:23]
That Paul once felt this is granted, but did he not afterwards say,
"`There is no condemnation to them that are in Christ Jesus,
who walk not after the flesh but after the Spirit`"?^
footnote:[Romans 8:1]
And did he not say,
"`The law of the Spirit of life had made him free from the law of sin;`"^
footnote:[Romans 8:4]
and, "`How can they who were dead unto sin live any longer therein?`"^
footnote:[Romans 6:2]
Does he not again say, "`I am crucified with Christ, nevertheless I live,
yet not I (not the natural, sinful self), but Christ lives in me?`"^
footnote:[Galatians 2:20]
"`I will dwell in them and walk in them says the Lord;`"^
footnote:[1 Corinthians 6:16]
and will the Lord dwell in an unholy place?
Can light dwell with darkness.
Now, Satan can and does indeed transform himself into an angel of light; yes,
he sits as God in the temple of God, showing himself to be God.
The imagining part in man is sure to be deceived,
and worship his appearance instead of the reality, for the world by its wisdom,
and man by his natural or humanly acquired abilities, knew not, nor ever can know God.
But, "`If any man,`" says Paul, "`will be wise, let him first become a fool,`"^
footnote:[1 Corinthians 3:18]
that his old eye may be closed, and a new eye, which alone can discern the things of God,
may be opened.

Christ says, "`Be perfect, even as your Father who is in heaven is perfect.`"^
footnote:[Matthew 5:48]
But modern Christians, as they call themselves, say there is no such thing as perfection.
Oh that they would consider whom they oppose by saying so!

Did not Paul desire those to whom he was writing to
"`cleanse themselves from all filthiness of flesh and spirit,
perfecting holiness in the fear of God`"?^
footnote:[2 Corinthians 7:1]
Does he not pray that others may be "`perfect and complete in all the will of God`"?^
footnote:[Colossians 4:12]
What does such plain and express language mean?
Oh the subtlety of that serpent, who can reason and argue the true meaning away!
And oh the lamentable state of those that are so deceived by him,
who are sitting down at ease,
with the vain imagination that what Christ has done will be sufficient,
without experiencing His work in them.
These have eyes but see not, and ears but hear not, in a true spiritual sense.

Again, Christ says, "`Swear not at all;`"^
footnote:[Matthew 5:34]
but modern Christians say, "`We may swear in some cases.
We will reason about Christ's words, and judge for ourselves what they mean,
and how far they are to be obeyed or not.`"
Though James says, "`Above all things, my brethren, swear not.`"^
footnote:[James 5:12]
Yet you say, "`We may swear such and such oaths.`"
O poor Christendom, how is your gold become dim!

Again, Christ says, "`Whosoever of you does not forsake all that he has,
cannot be My disciple;`"^
footnote:[Luke 14:33]
but now Christians can keep all--their own wisdom, their own wills,
the favor of the world, its riches and friendships, its fashions and customs;
though James says,
"`Whoever is the friend of the world, makes himself the enemy of God;`"^
footnote:[James 4:4]
and Paul says, "`If I yet please men, I am not the servant of Christ.`"^
footnote:[Galatians 1:10]

Further, John the Baptist, who was sent to prepare the way of the Lord,
describing the nature and effects of his Master's kingdom, said,
"`Now (mark the word 'now') the axe is laid to the root of the tree;
every tree that brings not forth good fruit, is hewn down, and cast into the fire.`"^
footnote:[Matthew 3:10]
What tree and what root is here meant?
Is it outward or inward?
Who can answer this question, but he who has felt the axe,
and the destruction (in measure) of the corrupt tree?
"`His fan is in His hand,`" he adds, "`and He will thoroughly purge His floor;`"^
footnote:[Matthew 3:12; Luke 3:17]
(mark the word "`thoroughly!`") What then will remain?
Oh! that professors of Christianity were concerned to know,
and were willing to part with all that stands in the way.
Oh, that they may know indeed what it is to be thoroughly purged,
instead of denying the possibility of it;
for it is a dreadful thing to deny or oppose the power of Christ.
This is a language which surely implies a complete,
effectual cleansing from all the pollutions of sin, even now in this life.

Our Lord Himself uniformly, in all His discourses, inculcated this doctrine.
In that most excellent sermon on the Mount,
He insists on the necessity of a righteousness superior to that of the law; for says He,
"`Except your righteousness exceed the righteousness of the Scribes and Pharisees,
you shall in no way enter into the kingdom of heaven.`"^
footnote:[Matthew 5:20]
What language can be plainer?
And that He did not mean an imaginary, merely imputed righteousness,
as I fear many vainly suppose, is evident from the conclusion,
where He draws the comparison between those who hear and do His sayings,
and those who hear and do them not;
thereby fully establishing the possibility of doing them.

And if due attention is paid to every part of that discourse,
I think it must be obvious that they who are of the happy number who not only hear,
but also do those sayings, and who our Lord likens to a building upon a rock,
on which they are able to withstand all opposition, will not be
"`miserable sinners doing what they ought not to do, having no spiritual health,`" etc.,
but will know a righteousness wrought in them far superior to that of the law.
For, as the law, the outward law, written on tablets of stone, speaks to outward actions,
so the law of Christ, written as the apostle says, in the fleshly tablets of the heart,
reaches to the root and source of the action.
For, whereas the law said, "`You shall not kill.`"
Christ forbids being angry without cause.
Again, the law said, "`You shall not commit adultery;`" but Christ forbids lust,
thus striking at the root.
The cause being removed, the consequence or effect must inevitably be done away.
Once more, the law said, "`You shall love your neighbor, and hate your enemy;
an eye for an eye, and a tooth for a tooth.`"
Christ says,
"`Resist not evil, love your enemies, do good to them that hate you;`"
with much more of like import,
which many who profess to follow Him seem to pay very little attention to--
as though it were an indifferent matter whether they do them or not.
But it may be well for such to consider whether our Lord would have said,
"`Be perfect, even as your Father in heaven is perfect,`"
if He did not actually mean they should be so;
and whether they who do as He there exhorts, will not be perfect.
I cannot conceive how it is possible to deduce any
other inference without grossly wresting the scripture.

"`You are My friends,`" He said at another time,
"`if you do whatsoever I have commanded you.`"^
footnote:[John 15:14]
"`He that loves me keeps My commandments.`"^
footnote:[John 14:21]
"`Not everyone that says unto me Lord, Lord,
(that calls me Master and honors me with their lips),
shall enter into the kingdom of heaven, but he that does the will of My Father,
who is in heaven.`"^
footnote:[Matthew 7:21]
"`If you know these things happy are you if you do them.`"^
footnote:[John 13:17]
For if a simple belief in Christ's sufferings, resurrection, etc. is sufficient to save,
to what purpose were all His discourses wherein He
repeatedly insists upon the necessity of regeneration,
a being born again, which certainly implies something more than a change of opinion,
a persuasion of the judgment, and a partial reformation.
For as He said to Nicodemus,
"`That which is born of the flesh, is flesh and that which is born of the spirit, is spirit,`"^
footnote:[John 3:6]
it obviously follows that they who are really born of the Spirit,
will become of the same nature as the Spirit.
Old things will be passed away, and all things become new, and all of God.
"`A little leaven leavens the whole lump;`"^
footnote:[Luke 13:21]
"`New wine must be put into new wineskins,`"^
footnote:[Mark 2:22]
with many other similitudes, plainly implying the necessity of a total, effectual change.

Again to confirm this great and necessary truth of freedom from sin,
He says to His disciples,
"`If you continue in My word, then are you My disciples indeed,
and you shall know the truth,
and the truth shall make you free,`" and to reprove their carnal ideas of a temporal,
outward freedom, He adds, "`He that commits sin, is the servant of sin,
and if the Son shall make you free, you shall be free indeed.`"^
footnote:[John 8:31-34]
That this freedom from sin, even from the power as well as the guilt,
is to be known in this life,
is certified again by His saying of those who die in their sins,
"`Where I go, you cannot come.`"^
footnote:[John 8:21]
Now if deliverance from sin is not known in this life,
we must of necessity die in our sins.
Therefore it matters not what knowledge a man has, what his faith is,
or what profession he has made, if he has not known deliverance from sin.
This point is so important, and a mistake therein liable to such harmful consequences,
that I am induced to dwell upon it,
knowing from my own experience how prevalent is the contrary opinion.

Indeed,
it is not hard to understand why people should prefer
deliverance from the guilt and punishment of sin,
without the power of sin being subdued; for we naturally love ease,
an ease which the cross of Christ is decidedly against.
So close does the cross apply, that it is, in our Lord's own words,
as cutting off a right hand, and plucking out a right eye.^
footnote:[Matthew 6:29-30.]
"`Whosoever,`" He says again and again,
"`does not bear his cross, and come after me, cannot be My disciple.`"^
footnote:[Luke 14:27]
The apostle bears testimony to this important truth, where he says,
"`They that are Christ's, have crucified the flesh with its affections and lusts.`"^
footnote:[Galatians 5:24]
Surely if lusts and affections--the very root and seed of sin--are slain,
what of it can remain?
In another place he says,
"`How shall we, that are dead to sin, live any longer therein?`"^
footnote:[ Romans 6:2]
And another apostle says, "`Whosoever is born of God, does not commit sin,
for His Seed remains in him, and he cannot sin, because he is born of God.`"^
footnote:[1 John 3:9.]

I have produced a few plain passages of scripture,
to show that deliverance from sin--a being cleansed from all
defilement thereof in this life--is not only possible,
but indispensably necessary; and that the contrary doctrine is fundamentally erroneous;
as it sets up the shadow instead of the substance,
an imaginary, instead of a real, holiness.
I may probably make some more observations on this most important point as I proceed.

I shall now offer a few remarks on some of the religious services usually performed,
comparing them also with the Scriptures of truth (which most
professors of Christianity acknowledge to be their standard or rule);
from which comparison I believe it will clearly appear
that these services are not what many call them,
i.e. 'means of grace`' and '`ordinances of God.`' Instead,
they seem rather to be the mere inventions of man,
set up in his own fallen wisdom as a substitute for the life and power,
which were lost in a long dark night of apostasy; not being the true worship of God,
but rather such bodily exercises as the apostle says, "`profit little.`"^
footnote:[1 Timothy 4:8.]
For let it be remembered that the great Author
of the gospel dispensation expressly declared,
"`that the true worshippers shall worship the Father in Spirit and in truth.`"^
footnote:[John 4:23]
And the apostle confirms this, saying,
"`We know not what we should pray for as we ought;
but the Spirit helps our weaknesses,
and makes intercession for us with groanings which cannot be uttered.`"^
footnote:[Romans 8:26]

Therefore, seeing that this necessary assistance is not at our command,
it follows that pretending to worship the Most High in a prescribed form,
or in the studied or extemporaneous productions
of man`'s own natural or acquired abilities,
in his own will and time,
without waiting to feel the influences and movings of the Holy Spirit
(in and through which alone true worship can be performed),
can be nothing better than will-worship,^
footnote:[The term will-worship comes from Colossians 2:23,
where Paul speaks of "`things which indeed have a show of wisdom in will-worship,
false humility, and neglecting of the body, etc.`"
The term is used to describe worship that is according to one's own fancy,
imposed merely by human will, and not by divine authority or assistance.]
whatever it may be called.
The Scriptures also repeatedly mention a growing in grace,^
footnote:[2 Pet. 3:18]
a going on unto perfection.^
footnote:[Hebrews 6:1]
How inconsistent then is the repeated and uniform acknowledgement,
"`We are miserable sinners, doing what we ought not to do,`" etc.?
Does this not obviously manifest, if truth be spoken,
that no benefit has been received,
notwithstanding the frequent (as it is claimed) seeking of the Lord?
But if it is true, as the Scriptures declare,
that Christ came to "`save His people from their sins,`"^
footnote:[Matthew 1:21]
then they who make such confession, acknowledge they are not of that number.
For clearly, if they are still miserable sinners, they are not saved from their sins,
however they may attempt to reconcile so plain a contradiction.

And this inconsistency is not confined to a particular part of the service,
for its appearance in the whole is equally obvious.
For at one time the people are heard confessing their sins and wickedness,
and shortly thereafter they are called upon to address the Most High with pure, humble,
penitent, and obedient hearts.
At one moment they acknowledge having erred and strayed like lost sheep,
but then declare they will show forth His praise not only with their lips,
but with their lives, giving themselves up to His service,
and walking before Him in holiness and righteousness
all their days (though still miserable sinners,
doing what they ought not to do, etc.). Can this running backwards and forwards,
one time saying one thing, another time quite the contrary,
be acceptable service to the God who searches the heart, tries the mind,
and requires truth in the inward parts?
And in repeating aloud the experiences of the royal Psalmist,
how is it possible but that many gross falsehoods must be expressed?
For if the words of the mouth do not express the real experiential language of the heart,
however excellent they may be, they are not words of truth,
but rather words of falsehood in the mouth of those who utter them.
I should hope a little serious consideration will convince of this.

Now, respecting the custom or practice of singing, I have a few observations to make.
Is it not inconsistent that they who have just before
been confessing their misery and wretchedness,
should appear so quickly and easily to forget all that, and immediately begin singing.
Surely this seems evidently to declare,
that they were not sincere in their acknowledgements,
or that they think it of very little consequence
whether their prayers are answered or not.
Is this not trifling with serious things?
I am fully persuaded that the common practice of
singing is only calculated to amuse the creature,
to please the outward ear,
whatever may be claimed of its warming the heart and kindling devotion.
And if those who practice it would be honest and candid,
I am of the opinion they would be constrained to acknowledge that amusement
is really the chief object--or why are they so pleased with tunes and music?
Can it for a moment be supposed that the Almighty is to
be honored by such a superficial conduct?
Surely not.
And with respect to its kindling devotion,
it may be well to remember what was said of those,
"`who kindle a fire,
and encompass themselves about with sparks; they may walk in the light thereof,
but they shall lie down in sorrow.`"^
footnote:[Isaiah 50:11]

I readily admit what is advanced to defend this custom, that our Lord and His disciples,
the night before He suffered, sang a hymn, but what or how we are not informed.
No doubt the matter and manner were both proper and seasonable.
And, that Paul and Silas in prison, sang praises to the Lord, I of course believe;
but I cannot conceive what argument can be deduced from this for the
present custom of singing whatever happens to be chosen for a service,
suitable or not--whether praise, profession, acknowledgement, or petition.
I find this outward,
prescribed singing very different from that which was recommended by the apostle,
"`Singing with the Spirit, and with the understanding,`"^
footnote:[1 Corinthians 14:15]
or, "`Singing and making melody in your hearts to the Lord.`"^
footnote:[Ephesians 5:19]
And I also believe,
that the true source of praise--even a grateful sense of the Lord's mercies--can be
better and more consistently expressed than in an outward jingle and sound.

It ought ever to be considered that God is a Spirit,
and that they who worship Him must worship Him in Spirit and in truth.
In other words, it is the language of the heart which He regards, not the words,
however excellent they may be of themselves.
Now I appeal to the Witness of God in every heart in
the consideration of the following question:
In view of the variety of conditions of those present,
and the distinct subject matter of each song--whether of praise, adoration, confession,
petitioning, etc.--is it likely that the congregation,
with propriety and in the fear of the Lord,
in whatever state or condition it may be at the time,
is rightly prepared to sing whatever happens to be given out?
It appears to me impossible that a whole congregation could be in the same frame of mind,
considering the various dispensations of the Lord's providence towards His people.
Consequently, it follows of course, that if all sing,
some must utter words with the mouth which are far contrary to the language of the heart,
which is so far from being acceptable to the Lord,
that I am persuaded it is hypocrisy and an abomination in His sight.

I am now speaking more particularly concerning those
who have attained to a measure of the grace of God.
Ask yourselves seriously:
Is outward singing intended or calculated to please the carnal ears of men,
or a holy God?
Why such anxiety about tunes, voices, and music?
Is the Lord to be pleased with such earthly things?
Oh no; you cannot suppose it.
Consider from what root it springs, from the old man or the new;
and remember His axe is laid to the root, to destroy all that is of the earth,
of our fleshly nature.
I have considered those passages in the New Testament where the subject is mentioned,
and feel confirmed by them in my opinion of the inconsistency of public singing.
The apostle speaks of singing with grace in the heart,
of making melody in the heart to the Lord,
and not of making a noise with the tongue unless that proceeds from the heart--which,
how seldom it does in public singing I appeal to every considerate mind to consider.

I am convinced in my own mind, considering our situation here,
and the power and devices of the enemy, and our own inbred corruptions,
that it would be more appropriate to watch and pray, and be ever on our guard,
waiting to feel the light and power of Christ to
discover and subdue the hidden things of darkness,
than to manifest that trifling, careless spirit,
which too commonly attends public singing.
Then, as children of the light we might walk in the light,
and find the blood of Jesus Christ, His Spirit and Power, cleansing us from all sin.

And tell me,
how can those present who are living in open and avowed
opposition to God join in singing without uttering gross,
abominable lies?
Are we not accessories to this?
Is it not expected that when a psalm or hymn is given out, all who are present will join?
Then let it not be said,
'`How can we help the abuse of it?`'
Should we not
rather set them an example of truth and righteousness,
and not approve any practice that has a tendency to promote lightness and irreverence?
Oh! my friends, this cannot be acceptable to the Lord,
who requires truth in the inward parts.
I recommend to your serious consideration what the Lord says in the
1st chapter of Isaiah respecting the ordinances of His own appointing,
when not done in a proper spirit:
"`'To what purpose is the multitude of your sacrifices to Me?' says the LORD.
'I have had enough of burnt offerings of rams and the fat of fed cattle.
I do not delight in the blood of bulls, or of lambs or goats,'`" etc.

I perceive every day more and more an evident departure from the simplicity of Christ.
Where is the daily cross borne?
Observe the appearance of the professors of Christianity.
What difference is there from the world?
My friends, these things ought not to be.
Bear with me, I beseech you.
I am much concerned for the honor of our profession.
If the cross is truly borne, all self-seeking and self-pleasing will be done away,
and the fruits of the Spirit will be more evidenced in the
gravity and solemnity of the true Christian profession.
May the Lord set these things home upon every heart,
that there may be a concern to offer unto Him an acceptable sacrifice,
which more than once is said to be a broken and contrite spirit.

"`Blessed are you that mourn,`" says Christ, "`for you shall rejoice;`"^
footnote:[Luke 6:21]
which rejoicing, I conceive to be a grateful sense of the Lord's mercies,
and a showing forth of His praises not only with our lips but in our lives.
O my friends, turn into your own hearts; "`Behold,`" says Christ,
"`the kingdom of God is within you.`"^
footnote:[Luke 17:21]
Look not without for what I am persuaded is only to be found within.
It is not much hearing or much speaking that brings true peace to the soul;
for the ear is never satisfied with hearing.
Do we not see professors of Christianity running here and there,
as though the more they heard, the better they should be,
encompassing themselves with the sparks of their own kindling?
But what says the Lord?
"`You shall lie down in sorrow.`"^
footnote:[Isaiah 50:11]
I am fully convinced it is for lack of this looking inward,
and waiting to feel the power of the Lord there, judging and subduing sin,
that there is so much talk, so much outward show,
and so little spirituality in the lives and conversation of the people.

Alas, my friends, I fear that many of you, (agreeably to your own confession),
are in a miserable condition.
Now, permit me to prevail upon you to consider,
whether your continuing year after year miserable sinners is
not the consequence of your prayers not being heard.
And let a concern arise to enquire whether you have been seeking aright or not;
for our Lord promised plainly and expressly, "`that they who seek shall find.`"^
footnote:[Matthew 7:5]
Now, what have they found, who continue (as they acknowledge)
'miserable sinners, doing what they ought not to do,' etc?
Do they not rather confess that the means they have
used are insufficient to cleanse and heal them;
that they have not rightly applied to the Great Physician, to the balm of Gilead,
"`to that tree, whose leaves are for the healing of the nations;`"^
footnote:[Revelation 22:2]
but rather have been
"`spending their money for what is not bread, and their labour for what does not satisfy,`"
instead of "`hearkening diligently unto the Lord, and eating that which is good,`"^
footnote:[Isaiah 55:2]
that true bread of life, of which our Lord said,
"`he that eats of this Bread shall live forever?`"^
footnote:[John 6:58]
It may be well to seek after these means before the possibility of a cure is denied;
lest you thereby deny the power of God, that He is not able to
"`cast out the strong man, who keeps his palace and his goods in peace.`"^
footnote:[Luke 11:21]
The apostle speaks of some, "`who had a form of godliness but denied the power thereof.`"^
footnote:[2 Timothy 3:5]
Now, it may be well to consider, in what can the power of godliness be known,
but in dominion over its adversary, which is sin.
And do not they who deny the possibility of sin's being subdued,
deny the power of godliness?

I have often wondered, how those who plead for the necessity of sin,
strongly claim to value the Scriptures, saying, "`the Scriptures are the rule!`"
But the Scriptures uniformly insist upon the necessity of holiness;
not an imaginary holiness, but a real purity of heart and of life.
"`Without holiness,`" said the apostle, "`no man shall see the Lord.`"^
footnote:[Hebrews 12:14]
"`Be you holy in all manner of conduct, because it is written, 'Be holy for I am holy.'`"^
footnote:[1 Peter 1:15.]
"`Present your bodies, (mark, your bodies) a living sacrifice, holy, acceptable unto God,
which is your reasonable service.`"^
footnote:[ Romans 12:1]
Professing Christians talk much of the blood of Christ;
it is a subject often in the mouth,
but what measure of the nature and effects of it is known,
let their own acknowledgements testify.
The apostle declares that it "`cleanses from all sin.`"^
footnote:[1 John 1:7]
Now how those who continue
'miserable sinners, doing what they ought not to do,' etc.
can be cleansed from all sin,
I leave to the considerate mind to judge.

It is with me now to answer some objections to this important truth,
and to remark upon some passages of Scripture,
with which those who deny the possibility of sin being subdued,
endeavor to cover themselves.
First, that Scripture which says
"`The heart of man is deceitful above all things, and desperately wicked, who can know it?`"^
footnote:[Jeremiah 17:9]
That the heart of every man, of every natural unregenerate man, is truly so,
I firmly believe.
But let it be remembered that the Lord promised to give
His people "`a new heart and a new spirit.`"^
footnote:[Ezekiel 36:26]
And dare any one say, that that heart is deceitful and wicked?
O, beware of depreciating the gift of God.
"`Blessed are the pure in heart, says our Lord, for they shall see God.`"^
footnote:[Matthew 5:8]
"`A good tree cannot bring forth evil fruit, neither can a corrupt tree bring forth good fruit.`"^
footnote:[Mark 7:18]
"`The seed on the good ground are they who in an honest and good heart,
having heard the word, keep it, and bring forth fruit with patience.`"^
footnote:[Luke 8:15]
For now, in the gospel dispensation, the axe is laid to the root of the tree, Matt. 3:10.
And what is the root of the tree but the heart,
from which all words and actions have their birth?
"`You blind Pharisee,`" said Christ,
"`cleanse first that which is within the cup and the platter,
that the outside may be clean also.`"^
footnote:[ Matthew 23:26]
And do you not in your written prayers,
request that God 'cleanse the thoughts of your hearts,
by the inspiration of His Holy Spirit?'--a most excellent petition.
But what is it to those who use it, and yet deny the possibility of its being answered?
Is it not a solemn mockery?
For if the thoughts of the heart are really cleansed, there can be no sin;
for sin defiles and pollutes the heart.

Another objection, is the language of the apostle,
where he speaks of "`a law in his members warring against the law of his mind,
and bringing him into captivity to the law of sin,`"
and that "`in his flesh dwelt no good thing.`"^
footnote:[ Romans 7:18]
That the apostle once was in that state, I think, is beyond a doubt;
and surely every real Christian experiences a
similar state till the strong man is cast out,
and the old leaven purged away.
But that Paul was in this state at the time of writing this epistle,
to me appears by no means credible from what he has written just before and after;
or else he must grossly contradict himself, which will hardly be allowed.
Certainly he was here describing the effects of
the law upon the carnal unregenerate mind:
for he says, "`The law is spiritual, but I am carnal, sold under sin.`"^
footnote:[Romans 7:14]
Now can it be supposed that the apostle was then still carnal?
Surely not; for having said,
"`The carnal mind is enmity against God,`" and
"`To be carnally minded is death,`"
and "`They who are in the flesh cannot please God;`" he adds,
"`But you are not in the flesh, but in the Spirit, if the Spirit of God dwells in you;
and if any man has not the Spirit of Christ, he is none of His.`"^
footnote:[Romans 8:6-9]
It consequently follows that, if the apostle was then in a carnal state,
he was none of Christ's, but at enmity against God.
But a little before, he said, "`Knowing this, that our old man is crucified with Him,
that the body of sin might be destroyed, that henceforth we should not serve sin:
for he that is dead is freed from sin.`"^
footnote:[Romans 6:6-7]
And in the 2nd verse, "`How shall we that are dead to sin, live any longer therein.`"
And in the 22nd verse, "`Being made free from sin, and become servants to God,
you have your fruit unto holiness, and the end everlasting life.`"
Now let this plain language, both before and after, written no doubt at the same time,
determine whether the apostle was then in a carnal and unregenerate state or not.

And though he elsewhere says,
"`Not as though I have already attained, or am already perfected,`"^
footnote:[Philippians 3:10]
I think this in no respect favors the construction that many put upon it,
as implying that the apostle was then in a sinful state.
Rather, this Scripture seems to work against them,
as it plainly condemns the notion of being perfectly
and forever justified by a mere imputation,
and evinces the danger of sitting down at ease,
resting satisfied with an imaginary justification.
For in another place, speaking of the Christian progress,
Paul states he did not run with uncertainty, or fight as one that beats the air,
yet he found it necessary to keep his body under and bring it into subjection,
or there was a danger, notwithstanding he had preached to others,
of his being still a castaway.^
footnote:[1 Cor. 9:26-27]

Another objection against the necessity of knowing freedom
from sin is taken from the words of the same apostle,
where he says, "`By grace you are saved, through faith, and that not of yourselves;
it is the gift of God, not of works, lest any man should boast.`"^
footnote:[Ephesians 2:8-9]
In answer to which,
I believe it is very necessary to distinguish between the works of man,
which he does in his own will and strength, and those works which are wrought by God.
Perhaps it is from not rightly knowing this
distinction that people cry out against works,
as though they were all self-righteousness.
Now indeed, the works of man, of the unrenewed carnal mind, yes even the best of them,
are as filthy rags.
But I think there should be a great care not to join the works of God
(those which He works in His people) with man's own works;
for in the very next verse the apostle says, "`You are His workmanship,
created in Christ Jesus unto good works, which God has before ordained,
that we should walk in them.`"
That this is by grace, I believe no real Christian will deny, but will,
with humble gratitude in all his progress, acknowledge with the apostle,
"`by the grace of God I am what I am.`"^
footnote:[1 Corinthians 15:10]
This is the grace which the same apostle declared,
"`has appeared to all men,`"
(mark that, not to any particular part of men)
"`and teaches that, denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly, in this present world.`"^
footnote:[Titus 2:11]
He does not say grace teaches that we must continue in sin.
"`What?`" says he in another place,
"`shall we continue in sin, that grace may abound, God forbid.`"^
footnote:[Romans 6:1]
And that this is also through faith, who will deny?
for "`without faith it is impossible to please God.`"^
footnote:[Hebrews 11:6]
But the apostle speaks of a dead faith,^
footnote:[James 2:17]
a faith which the devils have,^
footnote:[James 2:19]
and a true faith which, it is said, "`works by love,`"^
footnote:[Galatians 5:6]
purifies the heart,^
footnote:[Acts 15:9]
and overcomes the world.^
footnote:[1 John 5:4]
Now what faith have those who say,
they are "`tied and bound with the chain of their sins,
that they are miserable sinners having no spiritual health in them,`" etc.
The tree is known by its fruit.

And I have heard the words of our Lord to those whom He healed
of diseases pleaded as an excuse for continuing in sin,
just so long as we have a measure of faith, such as,
"`Your faith has saved you;`" "`Your faith has made you whole,`"^
footnote:[Matthew 9:22; Mark 5:10,34:52; Luke 7:50-8:48, etc.] etc.
But let it be remembered,
that those to whom the Lord spoke these words were completely cured,
receiving "`perfect soundness;`"^
footnote:[Acts 3:16]
and I believe, there is a remnant in this day,
who witness the same works spiritually accomplished by the powerful
operation of the same Word in their hearts--even a being made whole,
a being healed of the great disease of sin,
which was prefigured by the various cures performed on the bodies of the people.

One more argument commonly adduced is where the apostle says,
"`If we say we have no sin we deceive ourselves and the truth is not in us.`"
But a due attention to what follows does not favor the
idea that he was then in that sinful state;
for he adds, "`If we say we have not sinned,`" plainly alluding to time past,
and continues, "`if we confess our sins, He is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`"^
footnote:[1 John 1:8-9]
And knowing that all "`unrighteousness is sin,`"^
footnote:[1 John 5:17]
they who are cleansed from all, surely can have none remaining.
And the same apostle speaks strongly in favor of this perfect cleansing where he asserts,
"`Whoever abides in Him does not sin`" and,
"`For this purpose the Son of God was manifested,
that He might destroy the works of the devil.
Whoever has been born of God does not sin, for His seed remains in him;
and he cannot sin, because he has been born of God.`"^
footnote:[1 John 3:6,8-9]

It is the sincere desire of my mind, that the people would consider for themselves,
and not take things of such importance upon trust.
Rather, let everyone attend to the advice of the apostle,
"`Let every man prove his own work, then shall he have rejoicing in himself,
and not in another, for every man shall bear his own burden.`"
"`Be not deceived,`" he adds just after, "`God is not mocked; whatsoever a man sows,
that shall he reap,`"^
footnote:[Galatians 6:4-8]
whatever be his opinion, knowledge or faith.
And in another place he says, though he had all knowledge,
could understand all mysteries, and though he had all faith, even to remove mountains,
yet he might still be as nothing.^
footnote:[1 Corinthians 13:2]

Therefore it might be wise to have a care of talking so highly of the Scriptures,
while the life and conduct are not agreeable thereto.
And remember the words of our Lord to some of old,
"`You search the Scriptures for in them you think you have eternal life;
and these are they which testify of Me,
and you will not come unto Me that you might have life.`"^
footnote:[John 5:39-40]
From this it appears, and it is worthy of the most serious attention,
that those who had the Scriptures and valued them,
so as to think they had eternal life in them, still would not come unto Christ,
of whom they testified;
and who alone was and is the "`life as well as the light of men.`"^
footnote:[John 1:4]
Therefore it may be well to take care of putting the letter, the testimony,
the declaration concerning an object, in the place of the object itself;
for our Lord did not say the Scriptures are the way;
but "`I am the way, the truth, and the life, and no man comes unto the Father but by Me.`"^
footnote:[John 14:6]
Indeed we must learn the difference between the letter, the outward word,
and the Word which was in the beginning,^
footnote:[John 1:1]
before the Scriptures, that is, "`the Word near in the mouth and in the heart;`"^
footnote:[Romans 10:8]
"`which is quick and powerful, sharper than any two-edged sword,
dividing asunder soul and spirit, joints and marrow,
and is a discerner of the thoughts and intents of the
heart...before whom all things are naked and open.`"^
footnote:[Hebrews 4:12]
Of Him, as I before observed, the Scriptures testify;
and without His all-powerful aid they remain a dead letter and a sealed book.
The apostle declared that the things of God can only be known by the Spirit of God.^
footnote:[1 Corinthians 2:11]
They are foolishness to the natural man.
Therefore I think we should be careful how we attempt to comprehend the
truths which are contained in the Scriptures by our own understandings;
but rather be willing, as the apostle recommends, to become fools,
that we may be truly wise.^
footnote:[1 Corinthians 3:18]

[.offset]
I would now offer a few remarks on those two ordinances
or ceremonies--Baptism and the Lord's Supper,
as they are called.

With respect to the first,
as it is practiced by those to whom I most particularly address myself,
little needs be said;
for the sprinkling of infants is not even an imitation of true baptism,
has no relation to it whatsoever,
nor do I believe there can be found a single precept or
example for it in any of the Scriptures of truth.
I am well persuaded it is, like many other things of the kind,
a Catholic invention from the times of darkness and apostasy,
as a substitute for the reality;
for it is not in any respect calculated to answer any good purpose whatsoever.
It may be well to seriously consider the language used during that ceremony,
where it is said that
"`this child is regenerate, and grafted into the body of Christ's church.`"
And in the catechism respecting it, it is said,
that the child "`is therein made a member of Christ, a child of God,
and an inheritor of the kingdom of Heaven.`"
Now let every considerate person solemnly ask himself whether
he really believes such effects are produced by this ordinance.
If it is possible that anyone can think so, his ideas of regeneration,
and of Christ's church also, differ very widely from mine.

Let it be considered also, what the people are taught to promise at this ceremony:
"`To renounce the devil and all his works, the pomps and vanities of this wicked world,
and all the sinful lusts of the flesh; to keep God's holy will and commandments,
and to walk in the same all the days of their lives.`"
Are they not here required to promise what they
believe and confess to be impossible to perform?
For surely if this were performed, they would not be
"`miserable sinners, doing what they ought not to do,`" etc.

Now, that baptism is necessary, absolutely necessary,
for every member of Christ's church, I fully believe;
but I do not believe that the application of water, even when rightly imitated,
is the one true baptism mentioned in Scripture.^
footnote:[Ephesians 4:5]
For it is not a putting away the filth of the flesh (which is all that outward,
elementary water can do), but "`the baptism of the Holy Spirit and of fire,`"^
footnote:[Matt. 3:11]–even a being baptized into the Name,
that is the nature of the Father, Son, and Holy Spirit,
and thereby experiencing the consuming of the earthly part in ourselves,
and a being cleansed and purified from all filthiness of flesh and spirit,
perfecting holiness in the fear of the Lord.
For the apostle says, "`As many as are baptized into Christ, have put on Christ,`"^
footnote:[Galatians 3:27]
not conceptually, but really; being buried with Him by this spiritual baptism into death,
even a death unto sin.
Thus, "`even as Christ was raised from the dead by the glory of the Father,
so you also will walk in the newness of life.`"^
footnote:[Romans 6:4.]
And again, "`If any man be in Christ he is a new creature, old things are passed away,
all things are become new, and all of God.`"^
footnote:[2 Corinthians 5:17]
And if all is of God, there can be no sin, for "`sin is of the devil, and not of God.`"^
footnote:[1 John 3:8]

With respect to that other ceremony, called the Lord's Supper,
I am sensible of the deep-rooted prejudice in favor of it.
Nevertheless, I feel no discouragement,
being under a belief that a glorious day is dawning when clouds and shadows,
signs and appearances, shall give place to reality, to the pure essential substance.
I am perfectly satisfied in my own mind respecting it,
and will endeavor to give my reasons,
why I believe it is not of that significance or obligation that many fix upon it.

That our Lord, the night before He suffered, took bread and broke it,
and gave it to His disciples, as also with the cup; and that He said,
"`this do in remembrance of me,`" I most certainly believe;
but that He appointed this to be an ongoing ordinance I cannot find.
I presume it will be granted that this meal
formed part of the feast of the Jewish passover,
for our Lord said,
"`With desire, I have desired to eat this Passover with you, before I suffer,`"^
footnote:[Luke 22:16]
and this was a remarkable type or figure of Christ, who was the very Paschal Lamb,
the substance or antitype itself.
And that the bread and wine, as a part of that Passover,
represented the body and blood of Christ to be broken and shed for the remission of sins,
I presume will also be granted.
But since there is certainly a very essential
difference between the sign and the thing signified,
let us consider a little, which is of the greatest consequence,
or whether both are of obligation.
I expect none to whom I address myself will deny that Christ
was and is really the substance and antitype of every type and
figure under the Mosaic ceremonial dispensation.
This then being one of those figures representing the death of Christ;
the substance being come, and the type fulfilled, what need is there now of the shadow?
Why not give place to the substance, as is freely done with other symbols and figures?

The apostle, writing to those in Corinth, remarks,
"`As often as you eat this bread, and drink this cup, you do show the Lord's death, till He come.`"^
footnote:[1 Corinthians 11:26]
This I think, by no means implies that it was a prescribed or required ordinance,
but rather shows only that those to whom he was writing
continued in the use or observance of the Jewish passover.
I do not think this cannot appear improbable,
when it is considered that for a time it was taught by some of the disciples,
that "`it was needful to be circumcised, and to keep the law of Moses.`"^
footnote:[Acts 15:5]
Therefore, it appears to me that those to whom Paul wrote, as yet, knew not,
in a spiritual sense, the coming of Christ; that is,
His spiritual appearance in their hearts.
And Luke seems to infer a similar case in Acts 19:2,
where he speaks of some who had been baptized with John's baptism, that is of water,
yet had not so much as heard whether there was a Holy Spirit,
the promised manner of His coming again,
spoken of in John 16:7.--"`Nevertheless I tell you the truth.
It is to your advantage that I go away; for if I do not go away,
the Helper will not come to you; but if I depart, I will send Him to you.`"

Again, the apostle says, speaking unto wise men (no doubt spiritually wise),
"`The cup of blessing we bless, is it not the communion of the blood of Christ.
The bread we break, is it not the communion of the body of Christ?`"^
footnote:[1 Corinthians 10:15-16]
Can it be supposed that he here alludes to outward bread and wine?
For if he did, then all who partake of that outward ceremony,
whoever or whatever they may be, have communion with Christ.
Surely this would be joining light and darkness, Christ and Belial,
righteousness and unrighteousness together,
in direct opposition to the same apostle's plain declaration to the same people.^
footnote:[2 Corinthians 6:15]
And elsewhere he says, "`You cannot drink of the cup of the Lord, and the cup of devils;
you cannot be partakers of the Lord's table and the table of devils.`"^
footnote:[1 Corinthians 10:20]
Now it is very obvious, that any can partake of the outward bread and wine,
therefore that cannot be the true cup and table of the Lord.
And what is recorded of the disciples breaking bread from house to house, in Acts 2:24,
I think by no means implies such a ceremony,
but rather a social way of living among themselves; as it is said,
"`they had all things common,`" verse 44, and, from what immediately follows,
"`did eat their bread with gladness and singleness of heart,`" verse 46,
plainly alluding to their common meals.

It is also, I think, very observable,
that when the apostles were assembled at Jerusalem to consider
what was necessary to be prescribed to the believing Gentiles,
this ceremony of bread and wine was not even mentioned.
Had it been necessary, it would surely not have been omitted,
considering the things which were then enjoined;
most of which have since been laid aside
(i.e "`to abstain from things polluted by idols, from sexual immorality,
from things strangled, and from blood.`")^
footnote:[Acts 15:20]
But our Lord's own words appear to me decidedly to disfavor the outward sign,
where He emphatically calls Himself the "`Bread of Life,`" saying, in John 6:46,
that "`His flesh is bread indeed, and His blood drink indeed,
and that whosoever ate and drank it had eternal life.`"
And in order to reprove their carnal ideas of outward eating and drinking, verse 52,
and to direct their minds to the spiritual substance, He adds,
"`What if you shall see the Son of Man ascend up where He was before,`" verse 62,
as though to say, how will you eat Him then?
undefined Not in outward bread and wine, for "`it is the Spirit that gives life, the flesh (or outward food) profits nothing`" verse 63.

I believe there are among those to whom I address myself,
some who are sensible of the necessity of this spiritual communion,
and are truly desirous to partake thereof.
Far be it from me to wound any of these.
I do tenderly salute them,
and feel a degree of unity with the least appearance of the true Seed of the kingdom.
I desire not to hurt the least plant of the Lord's own planting.
Yet let me say to these in a spirit of love and unity:
since this is acknowledged to be but a sign or token, why is it continued,
when others of equal authority and obligation are dispensed with?
For instance, that of circumcision, which our Lord Himself submitted to,^
footnote:[Luke 2:21]
and which for a time, even after His ascension, was prescribed by His disciples,
as I before quoted.
Why is this laid aside?
It may perhaps be answered that this sign, according to the apostle's definition of it,
represented the
"`circumcision made without hands, in putting off the body of the sins of the flesh.`"^
footnote:[Colossians 2:11]
I fully believe it did, and as it is equally true that bread and wine is also a sign,
there appears to me not a shadow of a reason why the one
should be continued in preference to the other--seeing that
the thing signified by both is of equal obligation.

Furthermore, it is worthy of observation, that the beloved disciple John,
in his relation of that night, makes not the least mention of the bread and wine;
but he is very particular in giving an account of our Lord's washing His disciples feet.
Now, why is this ceremony not observed in the church today,
for it appears to be even more particularly prescribed than the other?
For  Christ says, "`You call me Master and Lord, and you say well, for so I am;
if I then your Lord and Master have washed your feet,
you ought also to wash one another's feet, for I have given you an example,
that you should do as I have done unto you.`"^
footnote:[John 13:3]
Now where can there be found so strong an injunction for the bread and wine?
If it is answered,
that the washing of feet was a sign or figure to teach humility and love to each other,
which I readily admit it was,
I think it is necessary to prove the other to be something
more than a sign to support its continuance and preference,
which I expect will hardly be attempted.

And that the outward supper was not practiced or
observed as an "`ordinance`" by the apostles,
I think evidently appears from the whole tenor of their writings.
Indeed, Paul reproves some for being subject to ordinances, saying,
"`If you died with Christ from the basic principles of the world, why,
as though living in the world, do you subject yourselves to regulations--'Do not touch,
do not taste, do not handle,' which all concern things which perish with the using;`"^
footnote:[Colossians 2:20-21]
and does not outward bread and wine perish with the using?
The apostle well knew the true living bread was not of a perishable nature.
Again, he says, "`Let no man judge you in meat and in drink, or in respect to holy days,
new moons, or sabbaths, which`" he adds,
"`are a shadow of things to come, but the body, (or substance) is of Christ.`"^
footnote:[Colossians 2:16-17]
In another place he says, "`The kingdom of God is not food and drink,
but righteousness and peace, and joy in the Holy Ghost.`"^
footnote:[Romans 14:17]
And to some others he said
"`I am afraid for you, lest I have labored for you in vain;`"
because after they had known God,
and had tasted something of the substance,
they "`turned again to the weak and beggarly elements,
whereunto they desired again to be in bondage.
You observe days, and months, and times, and years,`"^
footnote:[Galatians 4:9]
which he had declared to be but "`shadows of good things;`" and I fear the same
language is too applicable to many who make a very high profession in this day.

From what I have observed on this subject, I think to an unprejudiced mind,
it must appear, first: that the true supper of the Lord is an inward,
spiritual communion--"`Behold,`" says Christ, "`I stand at the door, and knock:
if any man hear My voice and open the door, I will come in to him, and will sup with him,
and he with Me;`"^
footnote:[Revelation 3:20]
and second:
that the outward bread and wine was part of the Jewish ceremonial dispensation,
which was neither commanded as an ordinance,
nor practiced generally by the gentiles in the apostles`' days.
And I would just add, that if it were indeed a necessary ordinance, in other words,
if it is what many assert it to be, then the effects of it would be evident.
For our Lord said, "`Whosoever ate His flesh and drank His blood, had eternal life.`"^
footnote:[John 6:54]
Now I presume no one to whom I now address myself will
impute such an effect to the outward bread and wine.
How, therefore, can this be the true Lord's supper, since we nowhere read of two suppers.
I believe many are in a degree sensible of the
difference between the sign and thing signified,
the shadow and the substance;
and seeing that the substance or the reality is to be partaken of,
yes is an absolute necessity (for our Lord said,
"`Except you eat the flesh of the Son of Man and drink His blood,
you have no life in yourselves`"^
footnote:[John 6:53]),
surely it is of great consequence to rightly know which is the true supper.

I have no doubt but there are those who, in sincerity and uprightness of heart,
continue in the use of the outward sign; and far be it from me to judge these.
I have only a caution to give in love, that where signs are regarded,
may it be as unto the Lord, and not unto men.^
footnote:[See Romans 14:6]
I fully believe religion does not consist in observing, or in not observing,
outward ceremonies.
For as the apostle says, "`In Christ Jesus, neither circumcision avails anything,
nor uncircumcision; but a new creature.`"^
footnote:[Galatians 6:15]
It is not a name, a profession, or any outward observance.
But I am not without a fear that many regard such things as unto men,
and are in bondage to them,
and are so settled down at ease in them that they will
hardly hear the least objection to them.
Such perhaps must be left for a time.

So then, I have given some of my reasons for absenting myself from your communion,
and why I believe the worship there performed is not the worship which the Lord requires,
being not agreeable, but rather contrary to the Scriptures.
I do not find it (as is claimed) 'the means of grace,
and the ordinance of God,' but largely the invention and imagination of man,
being wrong in both principle and in practice: in principle,
because you are taught you must not expect deliverance from sin in this life,
whereas the Scriptures unanimously testify to the contrary; and in practice,
because you worship in your own wills,
and teach for doctrines the commandments of men
(which our Lord testified against in Mark 7:7)
yes, and in an unregenerate state, according to your own confession.
So that what I have heard while among you,
that '`your best services are polluted,`' is strictly true;
for while you continue in a polluted state, all your performances are polluted also.
"`For who can bring a clean thing out of an unclean? No one.`"^
footnote:[Job 14:4]
But it may be well to remember, and it stands as an unchangeable truth,
that "`the sacrifices of the wicked are an abomination to the Lord.`"^
footnote:[Proverbs 21:27]
Though we may amuse ourselves with the vain idea that all is well,
I do assuredly believe that to offer any acceptable sacrifice
or service we must know (experientially know) a being
"`washed, sanctified, and justified in the name of the Lord Jesus, and by the Spirit of our God.`"^
footnote:[1 Corinthians 6:11]

Therefore remember a language of old to some who had no health in them,
but were unsound from head to foot, as many confess to be now:
"`To what purpose is the multitude of your sacrifices?
Bring no more vain oblations, incense is abomination to me, the new moons and sabbaths,
the calling of assemblies.
I cannot endure iniquity and the sacred meeting.
When you spread forth your hands, I will hide My eyes, yes, when you make many prayers,
I will not hear.`"^
footnote:[Isaiah 1:11-14]
And consider the exhortation to them, "`Wash yourselves, make yourselves clean,
put away the evil of your doings from before My eyes: cease to do evil,
learn to do well,`" etc.
Then it is added, "`Though your sins be as scarlet, they shall be white as snow:
though they be red like crimson, they shall be as wool.
If you are willing and obedient, you shall eat the good of the land;
but if you refuse and rebel, you shall be devoured with the sword:
for the mouth of the Lord has spoken it.`"^
footnote:[Isaiah 1:13-14]
Oh, how awful is this denunciation, now being fulfilled around us!
It is the fervent breathing of my spirit, that this highly professing,
much favored nation, who have been calling abundantly upon the Lord with their mouths,
and honoring Him with their lips,
may avert the impending stroke by truly humbling themselves before Him.
And as His judgments are in the earth, may they indeed learn righteousness.^
footnote:[Isaiah 26:9]

I know, my friends, from a degree of experience,
that there are many and various appearances, signs, and shadows,
set up among professing Christians; some of which I have already pointed out.
I now wish to direct you, according to the ability I am at present favored with,
to the reality or substance itself.
For the inestimable treasure which I had long and in vain sought for without,
among these various appearances, I at last found to be within.
I can anticipate the surprise, and perhaps the indignation,
which the word "`within`" may excite in some minds, who may be ready to exclaim,
"`Can there be any good thing in man?`"
Yes, friends, the sovereign good, the only good, is to be found there;
and I desire your patient attention while I endeavor to remove that unjust, delusive,
and destructive idea, that nothing good is to be found in man.

I believe it is the grand artifice,
the most successful insinuation of the great adversary of mankind,
to divert the attention away from that alone which is able to
effectually destroy his kingdom or rule in the heart,
and to draw the mind to objects without--to the various similitudes
and appearances in what may be called Mystery Babylon.
This good thing then, though it is in man, is not of man.
It is not natural to him, but rather a free, spontaneous, unmerited gift.
What is it?
With reverence be it spoken: it is God Himself, given to the soul of man--a truth,
I believe of the utmost importance to be experientially known by every individual.
And indeed, this truth is abundantly testified to in the sacred writings,
as being the groundwork, the substance, the foundation of all real religion.
The language of it is repeatedly expressed by all professors of Christianity;
though the truth of it, the reality of it, appears far too little known.
Do you not frequently read,
"`I will dwell in them, and walk in them; I will be their God, and they shall be My people.`"^
footnote:[2 Corinthians 6:16]
"`If a man love me,`" said our Lord, "`he will keep My words,
and My Father will love him, and We will come unto him and make our abode with him.`"^
footnote:[John 14:23]
"`The Comforter, even the Spirit of Truth,`" proceeding from the Father, said He,
"`dwells with you, and shall be in you.`"^
footnote:[John 14:17]
"`Know you not,`" said the Apostle,
"`that Jesus Christ is in you except you be reprobates?`"^
footnote:[2 Corinthians 13:5]
"`Know you not that your bodies are the temples of the living God?`"^
footnote:[1 Corinthians 6:19]

I could multiply quotations of Scriptures to prove this great and important truth,
but am sensible that those to whom I address myself are well acquainted with the words.
You are frequently reading of "`Christ within, the hope of glory,`"^
footnote:[Colossians 1:27]
under various figures and types.
But what is the reason He is not known there?
It is an important question.
What is the reason, I again repeat it,
that Christ is so often declared in Scripture as being within,
yet notwithstanding so much talk and imagination about Him,
is not known to be there in reality?
I believe, friends, I can tell you the reason why He, the one great Foundation,
is not known where alone He can truly be known.
It is because He is not sought for there, but in something without,
some appearance or representation of Him, a knowledge gathered from men or books,
or from the history or outward letter, which, however highly it may be valued,
is merely notional.
The real experiential knowledge is only known by His internal appearance,
His "`second coming, without sin, unto salvation;`"^
footnote:[Hebrews 9:28]
and the operation and effects thereby produced.
For when He appears in His temple, "`He will sit as a refiner and a purifier of silver;
He will purify the sons of Levi, and purge them as gold and silver,
that they may offer to the Lord an offering in righteousness.`"^
footnote:[See Malachi 3:3]

"`The kingdom of God,`" said our Lord, "`comes not by observation.`"
Man with all his wisdom, is unable to comprehend it, neither shall they say,
"`Lo here is Christ, or lo there,`" not in any outward appearance,
"`for behold the kingdom of God is within you.`"^
footnote:[Luke 17:20-21]
"`Say not in your heart,`" said the apostle, "`who shall ascend into heaven,
that is to bring Christ down from above, or who shall descend into the deep,
that is to bring Christ up again from the dead.`"
He is not at a distance, but is "`the Word near you, in your mouth and in your heart.`"^
footnote:[Romans 10:6-8]

Our Lord represented this great truth by various objects or similitudes,
to convey spiritual instruction to His disciples.
He spoke of a treasure hidden in a field;^
footnote:[Matthew 13:44]
a seed sown in the ground;^
footnote:[Mark 4:26]
a grain of mustard seed;^
footnote:[Matthew 13:31]
a little leaven hidden in meal;^
footnote:[Matthew 13:33]
plainly alluding to this inestimable treasure as hidden in the heart,
the earthly part of man.
There were some of whom our Lord said,
"`they have ears but hear not;`" these could not
understand the spiritual meaning of His parables.
But to some He said,
"`Unto you it is given to know the mysteries of the kingdom of God.`"^
footnote:[Mark 4:11]
Now, friends, it is of great consequence to know of which number we are,
whether His words are still to us as parables,
or whether we know that which unfolds their true meaning.
"`I am the light of the world;`" said Christ,
"`he that follows Me, shall not walk in darkness, but shall have the light of life.`"^
footnote:[John 8:12]

Now the apostle says there is no communion between light and darkness.^
footnote:[2 Corinthians 6:14]
If we do not have this light, we must of necessity be in darkness.
There is a spiritual light, as well as a natural, and the great apostle to the gentiles,
in declaring His commission to preach the gospel,
said it was to "`turn people from darkness to light, from the power of Satan unto God.`"^
footnote:[Acts 26:18]
Of what importance then is it to be acquainted with this light,
by which alone we can discern between good and evil.
"`All things,`" said the apostle "`that are reproved, are made manifest by the light;
for whatsoever does make manifest is light.`"^
footnote:[Ephesians 5:13]
The Scriptures speak abundantly of this light, so that we may know what it is.
John the Baptist was sent to bear witness of this true light,
which enlightens every man that comes into the world.
(John 1:8-9) In Him, i.e. in Christ, was life, and the life was the light of men.
(verse 4) This light shines in darkness, even the dark heart of man,
though the darkness does not comprehended it.
(verse 5) This is the light of the glorious gospel which has
"`shone in our hearts to give the light of the knowledge of the glory of God
in the face of Jesus Christ.`"^
footnote:[1 Corinthians 4:6]

Therefore, friends, I caution you to beware of calling it a light of the natural man,
or a new light, as many have done.
For I believe this same light, if believed and obeyed,
will effect the same works spiritually in the heart, or inner man,
as it formerly did on the bodies of the people of Israel.
Thus I believe there is great danger in speaking evil of the light, for those who do,
confess they are strangers to it, and so are walking in darkness,
for there is but one true spiritual light.
And "`If we say we have fellowship with Him and walk in darkness, we lie,
and do not practice the truth; but if we walk in the light, as He is in the light,
we have fellowship one with another, and the blood of Jesus Christ His Son,
cleanses us from all sin.`"^
footnote:[1 John 1:6-7]

Our Lord Himself plainly declared that "`Everyone that does evil, hates the light,
and does not come to the light, lest his deeds should be reproved;
but he that does the truth comes to the light, that his deeds may be made manifest,
that they are wrought in God.`"^
footnote:[John 3:20-21]
Therefore it is not strange that those who plead for the
necessity of sin (which is evil) also speak against this light,
and call it by any other name so as to excuse themselves.
For the things which the light manifests to be evil,
are too dearly loved to be parted with,
while they can still persuade themselves they are secure in retaining them.

My friends, I speak from experience,
and do earnestly recommend a turning to this light within,
from all the 'Lo heres,' and 'Lo theres,' from the various appearances, signs,
and shadows set up by the will and wisdom of men, in the times of darkness and apostasy.
Turn to Christ within, the hope of glory, the true foundation,^
footnote:[1 Corinthians 3:11]
the rock against which (as it is faithfully abode in)
even the gates of hell shall not prevail,^
footnote:[Matthew 16:18]
nor all the opposition of men.
This I believe is the substance of every shadow, the reality of every outward appearance,
the Word near in the mouth and in the heart, the true anointing,
which is truth and no lie,
and which teaches all things without a need of man's teaching.^
footnote:[1 John 2:27]
This is the new covenant, graciously promised by the Most High.
"`I will put My law in their inward parts, and write it in their hearts,
and will be their God, and they shall be My people;
and they shall teach no more every man his neighbor, and every man his brother, saying,
Know the Lord, for they shall all know me,
from the least of them unto the greatest of them, says the Lord.`"^
footnote:[Jeremiah 31:33-34]

"`Behold`" said our Lord, "`the kingdom of God is within you.`"^
footnote:[Luke 17:21]
The seed of the kingdom which is sown in the heart is
too small for the eye of man's wisdom to discover;
it is still a stumbling block to the lofty professing Jew,
and foolishness to the worldly-wise Greek.
But those who hear its call and obey it,
find it to be "`Christ the power of God and the wisdom of God.`"^
footnote:[1 Corinthians 1:23-24]
This I believe is the new birth,
without which our Lord declared no one could even see the kingdom of God,^
footnote:[John 3:3]
a birth which is not of blood, nor of the will of the flesh, nor of the will of man,
but of God.^
footnote:[John 1:13]
For that which is born of the flesh, however high and attractive in its appearance,
is still flesh; and that which is born of the spirit,
however low and contemptible in the eye of man's wisdom, is spirit.

The gospel is a spiritual dispensation.
Our Lord promised that the Spirit of truth, inwardly manifested,
should guide into all truth.^
footnote:[John 16:13]
The apostles were not to leave Jerusalem till they had received it,^
footnote:[Acts 1:4]
and then we are informed, "`They spoke as the Spirit gave them utterance.`"^
footnote:[Acts 2:4]
We have no reason to suppose they used any prepared form of words,
nor that they spoke when or where they chose;
but we are frequently informed of their going or
forbearing as they were directed by the Spirit;
see Acts 8:29. 19:7, etc.
Nor are we to suppose that this influence and direction
of the Spirit was confined to any period of time;
for, our Lord said, "`Lo, I am with you always, even unto the end of the world.`"^
footnote:[Matthew 28:20]
What a departure from their example and precept is lamentably
conspicuous among most professing Christians today!
For these have invented various images, forms, and modes of worship,
which they can perform whenever they please,
evidently acknowledging that the influence and assistance of the Spirit is unnecessary,
or at least that they will go ahead whether He assists or not.
Surely it may be well to consider,
whether this is not offering strange fire before the Lord.^
footnote:[Leviticus 10:1]

The only true worship under the gospel dispensation is (agreeably to our
Lord's express declaration) that which is "`in Spirit and in truth,`"^
footnote:[John 4:24]
and the influences and movings of the Spirit,
(although so absolutely necessary, that no acceptable worship can be performed without them)
are not at our command.
How proper, yes, how needful then, is a humble, silent, dependent waiting upon Him,
who alone can administer this assistance.
Here the true preparation of the heart may be experienced,
to receive whatever He (who searches the heart,
and alone knows what is good for those who wait upon
Him) may be pleased to administer--whether immediately,
by His still, small voice in the secret of the heart; or instrumentally,
by whomsoever He may please to appoint.

"`They that wait upon the Lord,`" said the Prophet, "`shall renew their strength.`"^
footnote:[Isaiah 40:31]
It is the professed belief of most religious
assemblies that it is good to wait upon the Lord.
But, I think a little serious consideration may
determine to whom this promise in Isaiah applies.
Is it to those who, in solemn humble silence,
wait to feel the influences of the Spirit to instruct
and enable both in what and when to offer,
or what to receive from the Fountain of good?
Or is it those who are always ready to begin, either in a prescribed form,
or in the exercise of their own natural or acquired abilities,
whether they have the Spirit`'s assistance or not?
Indeed the plain and express meaning of the term,
"`waiting,`" appears to me to be a silent and attentive expectation,
whereby we more particularly approach the sacred presence of Him who searches the heart,
tries the mind, and requires truth in the inward parts.
Surely He cannot possibly be deceived or amused by the most
plausible expressions or the most eloquent language,
for He has decidedly condemned the practice of drawing near to Him with the mouth,
and honoring Him with the lips, while the heart is far from Him.^
footnote:[Isaiah 29:13]
Thus, it is needful to wait, silently wait, for the reception of spiritual power,
lest we should be like those who offer the sacrifice of fools.
"`Let not your heart,`" said the wise man, "`be hasty to utter anything before God,
for God is in heaven and you are upon earth; therefore let your words be few.`"^
footnote:[Ecclesiastes 5:1-2]
And "`Apart from Me,`" said our blessed Lord, "`you can do nothing.`"^
footnote:[John 15:5]

Yet the practice of many who profess to follow Him evidently
declares that they think they can do a good deal without Him,
for as to words and outward performances they are always ready.
The apostle plainly declared, that "`we know not what we should pray for as we ought,
but the Spirit helps our weaknesses.`"^
footnote:[Romans 8:26]
What then are all the arts of composition, and the powers of human eloquence,
without the Spirit`'s assistance?
Are they not but a sounding brass or a tinkling cymbal?
"`When you pray,`" said our Lord, "`use not vain repetitions as the heathen do;
for they think they shall be heard for their many words.`"^
footnote:[Matthew 6:7]
This counsel, I fear, is too applicable,
not only to those who use prescribed and formal prayers,
but also to many who favor extemporaneous productions;
for both often act as though prayer consists in outward expression--
an idea repeatedly condemned in the Scriptures of Truth.

The apostle, after saying we know not what to pray for, adds,
"`The Spirit Himself makes intercession for us, with groanings which cannot be uttered.`"
Christ called them hypocrites who prayed in order to be seen of men,
and directed His disciples to pray in secret to their Father who sees in secret.^
footnote:[Matthew 6:5-6]
The apostle also recommends a praying always,
"`with all prayer and supplication in the Spirit, and watching thereunto with all perseverance.`"^
footnote:[Ephesians 6:18]
And in another place, he exhorts to a "`continuing steadfast in prayer;`"^
footnote:[Romans 12:12]
and again to a "`prayer without ceasing.`"^
footnote:[1 Thessalonians 5:17]
From all of this I think it must be clear that there may be true prayer without words,
and there may also be words without true prayer.
No doubt there are some possessed of considerable abilities, a ready flow of words,
and a pleasing eloquent delivery, who can at any time when they please,
deliver what I have heard called an excellent prayer,
without waiting to feel that influence which can alone enable to
"`pray with the Spirit, and with true understanding.`"^
footnote:[1 Corinthians 14:15]
But though such exercises may produce a temporary emotion in both speaker and hearer,
I fear it will be found a fire of their own kindling, a mere appearance,
and not the effects of the live coal from the true altar.^
footnote:[Isaiah 6:6]
The same observations are equally applicable to
every other external performance of worship,
public or private; for however it may affect the outward ear,
or kindle sparks of temporary warmth, if it does not proceed from the immediate,
sensible movings of the Spirit of truth, it may rightly be called will-worship.

I have also had a fear that the language of old, where it was said,
"`They limited the Holy One of Israel,`"^
footnote:[Psalms 78:41]
is applicable to most professing religious societies,
where a particular man or set of men,
assume to themselves the exclusive right of teaching and preaching.
This practice I believe to be totally repugnant to the gospel dispensation,
and the uniform examples and precepts of Christ and His apostles.
For I fully believe that no human authority, call, qualification, or ordination,
can make a minister of Christ; indeed, this is the prerogative of Christ Himself.
Paul said he was made an apostle,
"`Not of men, neither by man, but by Jesus Christ and God the Father.`"^
footnote:[Galatians 1:1]
And, as I before observed,
the dispensation of the gospel being a "`dispensation of the Spirit,`"
the true ministers thereof are ministers of the Spirit,
and not of the letter.
They are not ministers of words only, even the words of Scripture,
but ministers of the "`Word of eternal life,`"
even that "`Word which was in the beginning, which lives and abides forever,`"^
footnote:[1 Peter 1:23]
which Word is "`living and powerful, discerning the thoughts and intents of the heart.`"^
footnote:[Hebrews 4:12]
Words may have, and no doubt do have, their service,
as the Spirit brings them to remembrance and gives utterance;
but to steal the words of Scripture (see Jer. 23:30-
31) and put them into a premeditated form,
however eloquently they may be delivered, I do not believe to be preaching the gospel.
They who are particularly called, qualified,
and sent by Christ Himself (as I believe every true minister is),
will not presume to preach or pray, when, where, or what they please;
but only as they are immediately moved and directed by the Spirit of Christ,
inwardly revealed (see Gal. 1:16),
who alone knows what is needful to be administered.
And such ministers, as they have freely received, so they freely give,
agreeable to our Lord's command in Matthew 10:8,
without any view to temporal interests whatsoever.
For as they are not their own,
they cannot dispose of their time or talents according to their own wills,
but according as He who has called them is pleased to direct.

To conclude: it is my hope that the few observations I have now offered,
may perhaps be sufficient to demonstrate the inward and
spiritual nature of the gospel dispensation;
and that signs and figures, and all external, ceremonial performances,
are totally abolished from that worship which
can only be performed in Spirit and in truth.

And it is hoped that these considerations may also evince that the
only necessary qualification for true worship is the influence and
direction of the Spirit of truth inwardly revealed,
and that this necessary assistance is not confined to times or places,
nor to any particular man or set of men.
And since the apostle declared,
"`A manifestation of the Spirit is given to every man to profit withal,`"^
footnote:[1 Corinthians 12:7]
so I believe there are no individuals except who are favored with a sufficient portion,
which, if properly attended to, would direct them into the paths of true judgment.
The Word, even the Word of eternal life, is near to all,
so that none need to look to men for instruction; but this same anointing,
if the mind is simply and unreservedly directed to it, teaches all things and is truth.^
footnote:[1 John 2:27]
Who is there, who has not felt its secret reproofs for evil, and its approbation for good?
To this true Teacher,
of whose all sufficient aid I have thankfully to acknowledge a degree of experience,
I do earnestly recommend the particular, unwearied,
faithful attention of every individual.

[.signed-section-signature]
John Spalding

[.signed-section-context-close]
Reading, 30th of the 7th Month, 1794.
