== Address

The following brief memorial, of the experience of a deeply devoted mind,
is deemed worthy of public notice,
as an additional testimony to "`the cloud of witnesses,`" we are already favoured with,
to the internal efficacy of the power and principle of Truth.
The writer was a valuable example of Solomon`'s observation,
"`Honourable age is not that which standeth in length of time;
nor that is measured by number of years: but wisdom is grey hairs unto men;
and an unspotted life is old age:`" being remarkably distinguished by a steady,
uniform devotion,
and dedication of heart to the pure cause of Truth and Righteousness on the earth;
which he believed himself called to maintain,
and to endeavour to promote by example and precept.
His memory is therefore very precious;
in particular to some who had an intimate acquaintance with him.
To these more emphatically,
"`he being dead yet speaketh,`" in the remembrance of his solid, wise deportment,
his fewness of words, and those seasoned with grace;
and his steady firmness towards opposers of principles and testimonies,
which he had not taken upon trust, but deeply examined their foundation,
nature and tendency; and being baptized under a living concern to support them,
as before observed, he dared not flinch in the day of battle,
but both in that society of which he became a member, and also amongst others,
he was deeply and awfully engaged to stand his ground in the divine ability afforded,
and to exhibit an example of ancient simplicity and uprightness;
as he observed to a friend in one of his letters, some months before his decease.
After pointing out his great concern in observing the declensions
amongst a highly professing and eminently favoured people,
and making various remarks on the importance of preserving as a wall of defence,
the religious discipline established among them, and not giving way to weakness,
in order to maintain a specious, merely external unity,
and by being indifferent towards those noble testimonies which his soul loved,
and was uncommonly bound to: he firmly, yet humbly, added, "`O my friend,
excuse my freedom; the cause of truth I have to believe,
though with a due proportion of fear I would express it,
is so deeply impressed upon my mind,
that neither the fear nor the love of any created being or thing,
can be permitted to obstruct or divert me from what may appear to be required of me.`"

In a great degree in this firmness he lived, bearing much opposition,
and the cross as related in the following memorial;
and yet more particularly known to some who were acquainted with him;
and thus firmly he died in great stability and peace, having little to say,
but that little was truly much in a small compass,
expressed at different times to a few friends who visited him near his end:
some of whom were also with him just at the solemn period:
and though in the midst of mourning,
were joyful witnesses and partakers of that solemnity and peace,
which proved as a seal to the deep concern, exercise,
and happy close of the dear deceased.
He was ill about three weeks of a fever;
and in the forepart of his illness expressed to a friend who visited him,
"`that there was no cause of discouragement to the right-minded.`"
Being asked at another time if he had any thing in particular to express to friends,
he replied, "`No; only my love: all is well: nothing stands in my way.`"
And thus he peacefully laid down his life, in the 30th year of his age,
the 30th of the 1st. Month, 1795.
