== Some Account, etc.

I shall pass over the early part of my life,
only observing I had been educated in a religious way.
I mention this, as at times, when I lived in London, where I served an apprenticeship,
in the midst of my dissipation, I frequently felt the reproofs of the Lord in mine heart,
but which were soon smothered in the vortex of pleasure.
After I had served my apprenticeship,
I returned into the country to assist my father in his business of a farrier, at Reading,
in the year 1786.
A little time afterwards, as I attended the parish church so called,
where a celebrated preacher officiated, I found an awakening power,
which produced not a little alteration in me.
I more constantly attended the services, public and private;
joined the more particular professors, and went on for several years as one of them.
I also abstained from vain company and conversation which I had before been addicted to,
so that I was one of the chief professors;
but I found a gradual wearing off of the force of the impressions I had received;
less dislike to worldly company; and the power of sin gaining the ascendency;
that I at times felt much uneasiness; particularly as,
on serious reflection I felt the strength of my lusts and passions,
and the evil propensities of my nature unsubdued;
notwithstanding my knowledge of the truths of the gospel, and the profession I made:
and observing and conversing with my fellow professors.
I found the same great anxiety of mind, and breathings to the Lord,
that he would make me indeed what I professed to be;
and what I was persuaded by the scriptures of truth, a true Christian might be: that is,
free from the power, as well as the guilt of sin.
Thus I went on till about the year 1792, often feeling the dominion of sin, and,
desiring deliverance from it; when I was led to consider the people called Quakers,
and was soon satisfied there was a manifest difference between them and others,
even in outward appearance, which when I considered,
I was convinced was more conformable to christianity than any others I had known;
most of whom followed all the fashions of the world, particularly in dress;
an inconsistency I frequently observed with much concern.
I then sought the conversation of some of them, and still found more simplicity,
more like the precepts and practices of Christ and his Apostles,
that I desired to know the principles from which such superior practices resulted,
and enquired for some of their writings.

The first book I think that I read, was William Penn`'s _No Cross No Crown,_
which much tendered my spirit,
and removed some unfavourable opinions I had received respecting Friends.
I then in some measure saw how far what I had known
before fell short of what that work directed to;
yet I continued attending at the parish place of worship;
having the most favourable opinion of the minister there,
and a particular esteem for him,
as a man who also frequently professed a particular affection towards me.
Once I remember, when I had so far deviated from my profession, as to go to a horse-race,
he sent for me, and kindly admonished me as a friend and overseer.
I mention this, as afterwards,
when it pleased the Lord to enlighten my mind more clearly,
and convince me of the necessity of leaving the form of worship I had been accustomed to,
it was a sore trial to me to leave him,
in a manner that I apprehended he would feel not a little concerned about.
The next book I read I think was Barclay`'s Apology,
which opened many things so clearly to me, that I could not but consent to them;
nevertheless there were some things that at first reading I could not assent to,
particularly respecting public worship.
I thought it needful there should be a time appointed, and somebody ready to officiate,
that the ignorant might be instructed: and that a man, taught as I apprehended,
of the Lord, and properly qualified, might at any time exhort or preach to the people.
I still attended the old place,
going occasionally to friends meetings on any particular occasions,
when some strangers were expected; whose testimonies,
though I could not but approve of them,
yet were not able to draw me from my former society;
but I found the work of the Lord going on by degrees.

At first, I think, I considered the ordinance of the Lord`'s supper, as it is called,
and was sensible I had never found any profit in it,
from the beginning of my partaking of it;
and though I had often heard others speak very highly of it,
as finding particular and extraordinary comfort and benefit in it;
and I often at the time earnestly desired to find the benefit of it as well as others;
yet it still remained a dead, unprofitable service: I therefore declined it entirely.
The next thing I think I observed, was the public singing.
I began to see a great inconsistency in that practice, particularly after sermon.
I could feel it had in myself as well as in others,
a manifest tendency to lightness of spirit,
and removing any serious impressions which might
have been received from the foregoing discourse;
that I soon left the place, immediately after sermon was ended.
It was not long however before I saw a gross inconsistency in the practice altogether,
when I weightily considered the matter contained in what was sung,
how impossible it was for a congregation of different kinds of
people to join in singing whatever might be given out,
whether suitable to their conditions or not; much of which, I was persuaded,
could not be said by any, without uttering gross falsehoods;
which I could not believe could be acceptable in the sight of the Lord.
I was in consequence constrained to give forth
some observations on the subject in writing,
addressed to the professors of religion, attending the place called St. Gile`'s Church.

[.embedded-content-document.address]
--

[.blurb]
=== "`A few observations concerning the custom of singing in public meetings of worship; by one, who has long been convinced of the inconsistency of it, and now calls upon everyone who professes to be a follower of the meek and lowly Jesus, to lay aside prejudice, and seriously consider the following remarks, which are offered in the fear of the Lord.

"`First, It ought ever to be considered, that God is a Spirit,
and they that worship him must worship him in spirit and in truth In other words,
it is the language of the heart which he regards, not words,
however excellent of themselves.
Now I appeal to the witness of God in every heart, considering the variety of conditions,
the different subjects, of praise, adoration, confession, petitioning,
etc. etc. contained in every collection, whether in the fear of the Lord any one,
in whatever state or condition he may be at the time,
can with propriety be ready to sing whatever may be given out.
It appears to me impossible that a whole congregation
(even if we except the ignorant)
can be in the same frame of mind,
considering the various dispensations of the Lord`'s providence towards his people;
consequently if that is not the case, it follows of course, that if all sing,
some must utter words with the mouth contrary to the language of the heart,
which so far from being acceptable to the Lord,
I am persuaded is hypocrisy and an abomination in his sight.

"`Again, it appears to me inconsistent also with regard to the other parts of worship;
for if the language of the heart is spoken in prayer, which often precedes singing,
and which implies a sense of our wants,
doth it not shew an indifference whether our prayers are heard and answered or not,
to begin singing immediately, perhaps very different in matter as well as in manner,
to what has been prayed for?

"`Again, after preaching, if the Lord`'s power is known and felt under the word,
is it not more likely to profit, if the mind is occupied in serious meditation,
than singing, which from my own experience, I can say,
has a tendency to divert the mind from solemn, serious reflection?
I am now speaking more particularly concerning those,
who have attained to a measure of the grace of God.
Ask yourselves seriously.
Is outward singing intended or calculated to please the carnal ears of men, or a holy God?
Why such anxiety about tunes, voices, and music?
Is the Lord to be pleased with such poor things?
Oh, no; you cannot suppose it.
Consider from what root it springs, from the old man or the new;
and remember the axe is laid to the root, to destroy all that is of the earth,
of our fleshly nature.
I have considered those passages in the New Testament, where the subject is mentioned,
and am confirmed by them in my opinion, of the inconsistency of public singing.
The apostle speaks of singing with grace in the heart;
of making melody in the heart to the Lord;
not making a noise with the tongue unless that proceeds from the heart;
which how seldom it does in public singing I appeal to every considerate mind.

"`I am convinced in my own mind, considering our situation here,
the power and devices of the enemy, our own inbred corruptions,
that it is more seasonable to watch and pray, to be ever on our guard,
and waiting to feel the light and power of Christ,
to discover and subdue the hidden things of darkness;
that as children of the light we may walk in the light,
and find the blood of Jesus Christ, his Spirit and Power, cleansing us from all sin;
than evidencing that trifling, careless spirit, too commonly, if not always,
attending outward singing.

"`I could say much more against it, but would not be tedious,
particularly respecting those that are without.
How seldom can such people, living in open and avowed opposition to God,
join in singing without uttering gross, abominable lies:
and are we not accessary thereto?
Is it not expected when a psalm or hymn is given out,
all present who are capable will join?
Then let it not be said, how can we help the abuse of it.
Ought we not rather to set them an example of truth and righteousness,
and not countenance any practice that has a
tendency to promote lightness and irreverence?
Oh! my friends, this cannot be acceptable to the Lord,
who requireth truth in the inward parts.
I recommend to your serious consideration,
what the Lord says in the 1st of Isaiah respecting the ordinances, of his own appointing,
when not done in a proper spirit.
I perceive every day more and more, an evident departure from the simplicity of Christ.
Where is the daily cross borne?
Observe the appearance of professors.
What difference is there from the world?
Sure, my friends, these things ought not to be.
Bear with me, I beseech you.
I am much concerned for the honour of our profession.
If the cross is truly borne, all self-seeking and self-pleasing will be done away,
and the fruits of the spirit more evidenced;
which I am persuaded will not be in the present practice of public outward singing,
often of words, as to the matter, scarce within the bounds of probability:
and I am convinced if people would seriously consider the manner,
it would appear very inconsistent with the gravity and
solemnity of the true Christian profession.

"`May the Lord set these things home upon every heart,
that there may be a concern to offer unto him acceptable sacrifice;
which more than once is said to be a broken and contrite spirit.

__"`Blessed are ye that mourn,`"__ says Christ,
(not ye that sing) __"`for ye shall rejoice;`"__ which rejoicing,
if it may be applied to the present state of the church here,
I conceive to be a grateful sense of the Lord`'s mercies;
and showing forth his praises not only with our lips but in our lives.
To conclude, my friends, turn into your own hearts; behold, says Christ,
the kingdom of God is within you;
look not without for what I am persuaded is only to be found within.
It is not much hearing or much speaking, that brings true peace to the soul;
the ear is never satisfied with hearing.
As a proof of that, do not we see professors running hither and thither,
as though the more they heard, the better they should be;
encompassing themselves about with sparks of their own kindling, but what saith the Lord?
__"`Ye shall lie down in sorrow.`"__
I am fully convinced it is for want of this looking in,
and waiting to feel the power of the Lord there, judging and subduing sin,
that there is so much talk, so much outward parade,
and so little spirituality in the lives and conversation of the people.

[.signed-section-signature]
"`J. Spalding`"

--

This I sent to the clerk,
at the same time I sent some reasons for the apparent change in me,
as absenting from the sacrament, so called;
and which I desired him to lay before the minister and others, at a prayer meeting;
which he seemed to object to, supposing me in an error,
and having a very unfavourable opinion of Friends principles.
I soon after had some conversation with him on the subject;
which rather confirmed me in my opinion than otherwise,
his arguments appeared so weak against Friends.
Thus I went on some little time longer, still attending mornings and evenings;
but attending Friends meetings in the afternoon.
About this time I read Sewel`'s History of the Quakers,
which I think removed every objection,
and confirmed me in my opinion of the truth of their principles.
Their severe sufferings, their patience under them,
and honest boldness before kings and rulers, convinced me,
that nothing but a divine power could have supported them.
I sought the company of some faithful Friends,
as I could discover in some I had been with, little more than the form.
I desired to know the power in myself, and to be truly taught of the Lord,
that I might not do any thing by imitation, or because others did so;
but retired often alone, to be instructed of the Lord, what to do and what to leave; and,
glory to his name, he was found of me,
and made those retirements precious and profitable to me,
revealing his will unto me by degrees, as I was able to bear it.
I now became acquainted with some solid Friends,
and was occasionally in company with them,
which excited the attention of my friends and neighbours;
so that there was much talk about me, and various reports were propagated respecting it,
most people thinking it very strange I should turn Quaker.

About this time I met with a considerable trial,
the death of my father whom I dearly loved.
I had long been persuaded in some measure of the vanity and
inconsistency of wearing black clothes on such occasions,
knowing it to be only a worldly custom:
and had often said to myself during my father`'s illness,
I would not put it on for any one except him;
but there appeared so many reasons why I should conform on his account,
that it was not till a little time before his death,
that it pleased the Lord to remove my scruples respecting it,
and strengthen me to bear such a public testimony, as of necessity that event occasioned.
And indeed much opposition I met with on account of it,
but the Lord supported me through all.
I then constantly attended Friends meetings.

About this time also I was concerned to write an
address to some who usually met on first days,
from different parts of the neighbouring country, to hear the minister,
at a private house; where I had occasionally attended, with other professors of the town.
I also wrote to the clerk, and sent him "`No Cross, No Crown;`"
soon after "`Barclay`'s Apology;`"
and to another intimate friend, who was very zealous, I wrote and sent,
"`Beavan`'s Primative Christianity Restored.`"
And though I desired in what I wrote to individuals, as well as the society,
that it might be put about for the perusal of any; I found little notice taken by any,
I thought they seemed rather to avoid me.
One steady experienced man, in a little conversation, observing,
he hoped I did not look for that in myself, which was only to be found in Christ,
I was concerned to write to him some little time after on the subject;
and sent him at the same time, "`No Cross, No Crown.`"
While I was exercised towards the society I had left,
I met with some more trials from other quarters; my relations complained of my silence,
putting unfavorable constructions upon it.
Indeed I had so much upon my mind, that I had little desire to speak much:
for being often in my way of business with people of consequence in the neighbourhood,
most of whom had always shewn me much attention and favour, now observing such a change,
though only in dress at first, they began to look rather strangely upon me.
The enemy of souls was not unmindful of my situation,
and raised many difficulties in my way; as the loss of their favours, and, of course,
my business;
the great offence my conforming to other things not yet done would give them:
such as the ceremony of the hat, the language, and their titles so highly valued;
these seemed indeed so great discouragements,
that my mind was at times sorely distressed.

I had some time felt an uneasiness respecting the performing some part of my business,
such as nicking and cropping horses, etc. punishing them for the sake of appearance,
to please the fancies of men.
When I began to mention my scruples, much opposition was made,
as the consequence must of course be the loss of much business.
I know not whether I was not too hasty in this matter, beginning in mine own strength,
and not waiting the due time; for I found when I was required to do it, I gave way,
which brought trouble upon me; till at last I was enabled to refuse several,
among whom was one for whom I did much business,
who on my objecting and telling him my reasons,
seemed very angry and reproached my changing my religion, etc.
He asked me to recommend some one to do it,
but I told him I could not recommend another to do what I thought not right to do myself.

This event occasioned some uneasiness;
I was blamed highly on the supposition I should soon lose my business;
but I answered in the words of our Lord,
__"`Except a man forsake all that he hath, he cannot be my disciple.`"__
I saw more and more how people could follow the ways, customs, and fashions of the world,
and use means not always the most honest to get its riches: so true is our Lord`'s saying,
__"`Where your treasure is there will your hearts be also.`"__
O! how few really deny themselves and take up the cross.

About this time came the quarterly meeting of a society I helped to establish,
called "`The Sick Man`'s Visitor,`" to relieve the wants of those in distress,
conducted by the chief and most serious of the professors,
a committee of whom met every week to transact the business of it,
and to hold a prayer meeting as they called it, at the same time singing, reading, etc.
Being the time I used to serve on the committee, I took the opportunity to write to them,
giving my reasons why I could not join in the services performed at those times;
also something more respecting the principles, etc. of Friends,
with what was upon my mind besides;
observing if any were desirous of more information on the subject,
or had any objections to propose respecting Friends principles,
I was willing to receive them.

Hitherto there had not been any material alteration in my dress,
except what I wore on first days; I still wearing a modern hat;
but now I found it required of me to make an alteration there; which,
as it was more conspicuous than any I had made, I found very trying;
nature being unwilling to bear the cross; but it pleased the Lord to strengthen me;
and indeed it caused much gazing, admiration, and ridicule, as I could perceive and hear,
though little was said directly to me, but the Lord preserved me,
and I thought I found rather a kindness of behaviour among the more
considerable of my neighbours when I attended in the course of my business,
particularly from the chief justice Eyre,
where I had apprehended not a little discouragement,
but I found through the mercy of my God, a very favourable intercourse.
And here I may observe respecting these things, I felt a little at a time required of me;
and as I was willing to give up,
the Lord was pleased to afford me strength to be faithful to him.

Now I am aware these things, respecting dress, etc. are,
in the eyes of man`'s wisdom despised, and thought of no consequence:
indeed of themselves, I am persuaded they are of no consequence,
or if done from a wrong motive may be rather injurious than otherwise;
yet when the Lord commands, it becomes his creatures to obey, and not reason about it,
whether it is of consequence or not.
When I felt a desire to reason about it, the example of Naaman the Syrian,
was brought to my remembrance.
When the prophet ordered him to wash seven times in Jordan,
his pride and wisdom were offended; he wanted some great thing done, somewhat pompous,
and agreeable to the ideas of his worldly mind;
and had not his servants been wiser than their master,
he might have continued in his disease; but the event proved,
how despicable soever the means appeared, it fully answered all he could wish;
therefore it is good for any one who feels occasionally the judgment of the Lord,
against any thing however trifling it may appear, not to consult with flesh and blood,
not to reason about it, but give up in simplicity of mind;
and then I am persuaded it will be found of more consequence than was apprehended;
for if we are not faithful in the little,
how can we expect the greater will be committed to us.
And indeed in this matter I have been mentioning, I found not a little advantage;
for before, when my appearance was not very different from the world,
my acquaintance would enter into familiar converse with me;
which too often had a tendency to divert my mind
from that seriousness I wished to preserve,
and leave unpleasant reflections afterwards;
but when they saw (in their eyes) my uncouth appearance,
it operated as a kind of check to lightness,
and preserved me from the snare of unnecessary worldly conversation;
so that I had the advantage of more retirement,
which I trust I can say I have found the most profitable seasons.
The apostle saith not in vain,
__"`If any man love the world, the love of the Father is not in him.`"__
And a follower of Christ will not be conformed to the world,
nor uphold whatever is of it, either in himself or others;
not merely because it is witnessed against in the scriptures,
but being influenced by the same spirit, which was in them,
he is taught by it to testify against the same the disciples of old did in their day.

It was a great grief and concern to me to consider,
that as it was a day of so great profession, many walking miles to hear,
what they supposed the gospel, preached,
our steeple house being generally crowded by people from the other parishes;
I say it grieved me,
that my leaving the fashions of the world which they all professed to deny,
should cause such amazement as it appeared to do even in professors;
which helped to confirm me in my opinion,
that how much soever they could talk about religion,
very little of the power thereof was known:
indeed had I not felt a want of the power of godliness, I should not have left them,
as there were many ties which held me both to the priest and people.
But it was that divine power I longed for; and nothing short of it could satisfy me,
and sure nothing but that could have supported me in
the different trials I soon had to encounter;
but the battle was the Lord`'s,
and his was the victory over every appearance of mine adversary,
and to him be all the glory.

For several months my mind was much exercised on various occasions,
the enemy assaulting me continually with reproaches from without and fears within.
My business seemed to decline, and I was reproved for over acting my part,
and informed that some of the society had said so.
It was great grief to me to observe some Friends, for whom I entertained great esteem,
not so faithful against worldly titles, as Esquire, Sir such-a-one; Mr. +++______+++,
etc. as I believed was required and practised by ancient Friends.
It gave the enemies much occasion against me.

About this time peoples`' minds were much agitated on political subjects,
the French having overturned all orders and distinctions,
which gave great offence to people in general; they called their days,
etc. as do Friends, instead of the old names.
I mention this because the adversary assailed me with
the suggestion that I should be deemed of their spirit.
I could expect little favour, though politics was a subject I thought little about,
and spoke less: believing as our blessed Lord said,
__"`My kingdom is not of this world,`"__ every true
disciple being influenced by the same spirit,
the attention as well as the affections will be engaged in things above,
not of this world, more than needful; and it had been some time before a concern to me,
to observe some of the society of Friends meddling with such matters,
more warmly than I thought consistent with their profession.

I was at times so sorely pressed, so burdened in spirit,
that I seemed as though my strength was broken, and was ready to cry out,
__"`The children are come to the birth, and there is not strength to bring forth;`"__
but still my desires were to the Lord,
who had hitherto supported me, that I might still experience him a God near at hand,
and not afar off:
for I felt how unable I was to move a step without his divine assistance.
So low was I reduced, that though I received several reviling letters,
which were clearly against the truth, I had not power to answer them;
being taught to leave the cause to the Almighty,
and not be anxious to justify myself before men,
but which may be an encouragement to any who may experience similar trials,
I felt a secret upholding, a consoling assurance,
that the Lord would plead his own cause,
and in his own time bring forth judgment unto victory;
and I desired that his hand might not spare, neither his eye pity,
till his work was accomplished to his own glory, however it might be with me.

Thus I continued some time, till it pleased the Lord to revive me; when,
though I had little business in comparison to what I had heretofore,
yet I was abundantly satisfied with an enlivening sense of the Lord`'s presence;
which infinitely surpassed all worldly goods,
so that in measure I knew the truth of our dear Lord`'s promise,
that whoever may be enabled to leave any thing for his name`'s sake,
shall receive an hundred fold even in this life, either in kind or in kindness:
and sure the comfortable sense of the approbation of the most High,
is of infinitely greater value than any thing this world can afford.
O! that the people, particularly the Lord`'s professing people,
may be encouraged to be willing to part with everything,
however near and dear to flesh and blood, that stands in the way,
which obstructs that divine communion with him we are taught to expect; for true it is,
except a man forsake all that he hath, he cannot be Christ`'s disciple;
and he is not a hard master, doth not require any thing to be parted with,
but what would really be injurious to our spiritual welfare;
though to man`'s carnal apprehension it may seem in some cases in a different light.
Man naturally loves ease.
The cross of Christ is not pleasant to flesh and blood, but, my friends,
if ever we know the truth of what Paul declares,
that "`they who are Christ`'s have crucified the flesh with its
affections and lusts;`" and the more readily we submit to the yoke,
I am persuaded we shall the sooner experience that subdued, which dislikes the cross:
then we shall know what our Lord said, that his yoke is easy and his burden light.

A fear had arisen in my mind, lest I should be beholding the mote in my brother`'s eye,
and not attending sufficiently to that power,
which could alone remove the beam out of my own;
and though my spirit was frequently grieved on hearing vain conversation,
and often seemed to feel a desire to reprove, yet I was afraid to cast a stone,
feeling myself not without sin,
and I had to remember and to desire to practise what is recorded;
to study to be quiet and mind my own business; and I think I can truly say,
that in stillness and retiredness I experienced a degree of peace,
and I trust a growth in grace: and I must acknowledge with humble thankfulness,
the condescending kindness of my heavenly Father,
in favouring me with much opportunity of retirement;
having comparatively but little worldly business,
for I sorrowfully found in those lawful engagements,
a very great difficulty of keeping in that straight line of duty,
which I believed was marked out for me.
In the course of conversation words would occasionally drop, which,
afterwards on reflection,
brought distress on my mind and I desired to be thankful that
I was enabled not to desire much of this world`'s goods,
but rather the reverse, and to be content with food and raiment.

It was a concern to me to observe among Friends,
on a young man`'s beginning business for himself
a conformity in some things with the world,
I thought to gain their favour and custom;
it appeared to me paying very dear for their assistance;
and I believed I could prefer working hard as a servant,
to the most profitable situation on such terms;
and fervent desires would frequently arise in my mind,
that all who profess to be followers of Christ, particularly Friends,
who profess more than most, would be concerned to practise our blessed Lord`'s advice,
to seek first the kingdom of God and his righteousness;
yea and seek nothing else till they had found it; then I believed by attending to that,
they would be divinely directed in temporal concerns, and preferring it above all things,
would be preserved from the too prevailing snare
of flattering the world for their support.
I have thought that people are often led to such practices,
by engaging in concerns which bring extraordinary expense upon them; which,
requiring more of the things of this world,
a greater difficulty is experienced in bearing a faithful
testimony against what they may be convinced is evil.
These considerations, through divine assistance,
induced me to be careful of confining my expenses in as narrow
a compass as I believed consistent with my situation;
and though for many years I had strong inclinations to enter into the marriage state,
I now experienced a check to every desire of the kind believing it was my
duty to keep myself as much as possible from the cumbers of this world,
and as a faithful soldier to be ready for whatever my
great Lord and master should require of me.

Near the close of the year, 1793, I wrote to the Friends of the monthly meeting,
to be admitted a member of society;
which Friends in due season expressed their unity and compliance with:
and here I would observe, that from my first acquaintance with Friends,
I could not but approve their caution, in not hastily admitting any into membership;
differing from most societies, who, I have perceived,
evince a kind of exulting eagerness in adding to their numbers.
And I can say that I did not feel an anxiety to be received into membership;
but rather to know that power which first gathered Friends into a society;
to experience an union of spirit with the faithful,
than any name or outward relationship:
and though a little before I wrote to the monthly meeting,
I had some apprehension of being drawn for the militia,
which would probably have exposed me to some severe trial, not being of the society;
yet convinced of the necessity of bearing my testimony against wars and fightings,
I was mercifully enabled to be still, and leave the event whatever it might be,
to the Lord, who had hitherto supported me,
and not apply for admission any sooner on that account.

The first meeting for discipline I sat in,
I felt a powerful concern to speak on a particular subject,
but considering my state of childhood in the society,
and a fear lest I should appear forward, I endeavoured to get rid of it,
and avoid speaking; yet it seemed rather to increase than diminish,
till just at the close, I expressed a few sentences,
and found in a little time the burden relieved, at least in a degree.

I was often sorrowfully concerned to observe in the
nomination of Friends to quarterly and yearly meetings,
a disposition to make excuses;
believing those meetings were established under the influence and power of divine wisdom.
I thought if there was a proper attention to the guidance of the same,
Friends would be directed in their nomination;
that the great Lord of the harvest would choose whom he
pleased to employ in any particular service;
and I thought there might be danger in lightly and hastily making excuses,
lest it should be a disobeying the call of the most High.
It appeared to me, that worldly concerns had too much influence;
that it was considered whether it would be convenient or not.
Now I knew from my own experience, that if an ear was open to listen to excuses,
enough would be presented against many services or duties,
as attending week day meetings, and others, in times of business.
But I saw or felt it was safest and best to have a single eye,
to have only one object in view, what the Lord required of me;
than to look on temporal concerns, whether it was convenient or not,
but simply give up and leave the consequence;
and I can with humble thankfulness and gratitude acknowledge the
inconveniences or losses I might have apprehended would be the consequence,
were changed into a comfortable sense of divine approbation,
and an abundant reward of peace.

The 28th of the 2d month, 1794,
being appointed by government to be observed as a
general fast and humiliation before Almighty God,
and the mayor of Reading sending out a bill,
desiring all sects and parties to observe it as required:
I felt a concern to write a few reasons, etc. why we,
the religious society called Quakers, could not observe it as required;
which were copied and handed about in manuscript.
One copy I sent to the clerk of the parish,
desiring him to lay it before their ministers, and as many of the people as might be.

[.embedded-content-document.address]
--

[.blurb]
=== A few reasons why the religious society called quakers, cannot observe, as required, the day appointed for a general fast and humiliation (so-called) before Almighty God.

[.alt.centered]
==== That the magistrates and people may know it is not from any contempt of authority, nor in rebellion against government, but that they may preserve a conscience void of offence towards God and towards man:

"`First,
Because we believe that the Lord alone hath a right and authority to
enact and require how and when he will be worshipped.
That all worship whatsoever performed in the will of man,
and which the spirit of Christ doth not lead into, is not acceptable unto the Lord,
who hath declared, that
__"`in vain do they worship me, teaching for doctrines the commandments of men;`"__
and that __"`the true worshippers must worship in spirit and in truth.`"__
"`Therefore we believe,
that it doth not belong to man to impose modes and forms of worship, and if,
in compliance with the will of men, any should conform to such pretended worship,
the conscience not being clear, nor the heart rightly engaged in the service,
it would be hypocrisy in the sight of God,
and sin to the person so complying:`" for __"`whatsoever is not of faith, is sin.`"__

"`Secondly, Because we believe, it is not the fast which the Lord hath chosen,
or will approve of, according to what he hath declared by the prophet Isaiah,
and elsewhere, as for a man to afflict his soul for a day,
and to bow down his head as a bulrush.
And our Lord called those hypocrites, who desired to appear unto men to fast;
and commanded his disciples to anoint their head and wash their face,
that they might not appear unto men to fast, but unto him who seeth in secret;
who doth not look on the outward appearance, but upon the heart,
and who requireth truth in the inward parts.
And by the prophet he declared, that the fast which he had chosen,
was to loose the bands of wickedness, to feed the poor, clothe the naked,
etc. that then he would accept their prayers.

"`Thirdly,
Because it is required to implore the blessing
of Almighty God for the success of our arms,
which we believe is repugnant to the spirit of Christianity;
as Christ is the Prince of Peace, who did not come to destroy mens lives,
but to save them; and commanded his disciples not to resist evil,
but to love their enemies, and to do good to them that hate them.
Therefore in obedience to these commands,
through the influence and assistance of the spirit of Christ,
we cannot willingly think or do evil to any, whatever they may intend to do unto us;
but are enabled to commit ourselves to divine protection,
without the use of any carnal weapons,
assuredly believing the Lord will preserve all those who faithfully confide in,
and obey him.

"`For these reasons, and not from obstinacy, or perverseness,
or any disrespect to those in authority, we cannot keep our shops shut,
or in any manner directly or indirectly, uphold or countenance such a custom.

"`It is believed by a remnant, who are secretly mourning for the abominations of the land,
and travailing in spirit, that truth and righteousness may abound,
that there is great cause for fasting and humiliation before Almighty God;
for the transgressions of the people are multiplied against him,
so that there is reason to expect that the Lord will
visit with his rod even this highly favoured country;
and it is their secret desire that as the judgments of the Lord are in the earth,
the inhabitants thereof may learn righteousness.
But, friends, your pretended humiliation for a day, with your lips confessing your sins,
and again returning to your old course, is only mocking God, who will not hear,
though you make many prayers, and cause your voice to be heard on high,
while your hands are full of blood,
while you are desiring the destruction of your fellow creatures;
for that spirit is not of God, for God is love, and whoever are led by the spirit of God,
will love their fellow creatures, and not desire their harm.
Therefore, friends, consider what spirit you are of,
before you presume to draw near to the most High,
who is not to be honoured with the lips, while the heart is far from him,
which it is and ever must be, while defiled with the pollution of sin;
but seek for that new heart and new spirit which God hath promised;
and remember a language of old, to those who pretend to honour him with their lips,
while their hearts are far from him:
__"`Wash ye, make ye clean,
put away the evil of your doings from before mine eyes;
cease to do evil learn to do well.`"__
Then (and not till then, though you make never so many prayers,
and afflict yourselves never so much) the Lord
will hear your prayers and regard your petitions.

--

[.offset]
A few months after I also wrote a few reasons why we
could not illuminate our houses on any occasion;
as friends, in some places, had suffered considerably on that account.

[.embedded-content-document.address]
--

"`Whereas we the religious society of people called Quakers,
are accused by some of being disaffected to government,
because we do not illuminate our houses, as our neighbours do, on particular occasions;
this is for the information of any who may be desirous of knowing why we thus differ:
that it is not from any political motives,
nor to express any disapprobation of those who are in authority; but as Christians,
professing to walk in the fear of the Lord, in a holy life and conversation,
we believe such superficial demonstrations of joy inconsistent with this our profession,
on any occasion whatever;
but as it sometimes happens that such customs are in
consequence of a supposed advantage gained in war,
we cannot believe as Christians uninfluenced by any political considerations,
that there can be any real cause of rejoicing, but rather of mourning,
for the destruction of our fellow creatures,
and to lament the prevalence of those __"`lusts from whence,`"__ as the apostle says,
__"`come wars and fightings.`"__
Professing also to be followers of Christ, who is the Prince of Peace,
of whose kingdom it was prophesied __"`that they shall beat their swords into plough-shares,
and their spears into pruning hooks, that nation shall not lift up sword against nation,
neither shall they learn war any more,`"__
we believe wherever this kingdom is established in the heart of any individual,
the warring,
sighting nature will be subjected by the peaceable righteous sceptre of Christ;
who enjoined his followers not to resist evil, but to love even their enemies:
therefore we cannot, without subjecting ourselves to the displeasure of the most High,
conform to any custom, which countenances or upholds such practices.`"

"`But though we differ from the rest of our countrymen, we are not enemies to our country:
but our prayers are to the God of the spirits of all flesh, that he
__"`may please to break the bow, and snap the spear in sunder,
to cause wars to cease to the ends of the earth;`"__
that the people may turn every one from the evil of their ways,
and serve him alone from whom every blessing is received:
then would righteousness and peace meet together, and abound in the earth to his praise,
and to our present and eternal felicity.`"

--

I had for some months, at different times, as I apprehended the concern revive,
wrote an address to the professors of religion,
particularly those who attended the place I had left.
Feeling a concern to have it printed, I waited from time to time to feel it clearly,
as appearing in public in any manner of such a nature,
was to me a most weighty consideration; I was fearful of moving in mine own will,
but at length I apprehended the time come for its publicly appearing,
and submitted it to the inspection of several Friends of our meeting,
for their approbation of its being laid before the morning meeting in London;
being unwilling to move without the full concurrence of Friends.
It met with their approbation and consent, and it was going to be sent to London,
when a member of that meeting happened to come to our town.
Friends advised it to be shewn to him, who expressed a fear,
that as I was so lately come among Friends, if it was not quite approved of,
it might be a discouragement to me,
and recommended if I was easy to let it rest a little longer.
I seemed willing to find an excuse,
and to get rid of the burden without its publicly appearing; and laid it by,
not feeling the concern again revive with sufficient power:
but I had at times to fear whether I had not too hastily got rid of it,
and let the right time pass by.
May the great Master not impute rebellion to me, but have in this matter,
as I have at other times experienced, a gracious condescending regard to my weakness;
for I have desired to be made willing to be completely given up to his service,
and follow him wheresoever and howsoever he may require;
the frequent breathing of my spirit is,
that the inward ear may be so opened that I may be able to distinguish
between the Master`'s voice and every appearance of the adversary,
and all willings and runnings of the creature.

In the year 1794, I was at the yearly meeting in London, which held, I think, nine days,
and notwithstanding the nature of my business, I was made willing to give up the time,
and have with thankfulness to acknowledge I found no loss,
but the invaluable reward of peace.
Surely the Lord is not a hard master,
but whatever is given up under a sense of his requiring, is abundantly restored,
yea as an hundred fold.

A little time after being at an appointed meeting where no regular one is held,
under an apprehension of duty, I spoke a few words.
And here I would observe,
I had long a sense as though I should have to appear in this service,
and often felt a word arise in meetings, but was fearful of moving in my own will,
of running before I was sent; remembering the command of old,
__"`He that hath my word let him speak my word faithfully; what is the chaff to the wheat?`"__
I desired that there might be no mixture, nothing of the creature,
but that the master might prepare the offering wholly;
yet I often found a similar testimony to what I felt arise, delivered by another friend.
I would willingly have been excused the service, the prospect being far from pleasant,
at least to that which would prefer ease,
yet I was desirous that I might be willing and
able to give up to whatever the master required;
I seemed only to wish to know quite clearly, beyond the least doubt,
when and what to speak.
Perhaps I expected a clearer evidence than was meet, or made it an excuse to refrain,
till after one first day meeting, not giving up to speak a word,
I felt the reproofs of the most High so sharply, till next meeting,
that though very unwillingly, and after much inward wrestling against it,
I found it safest to give up, and was in a degree sensible,
that it is better to appear as a fool unto men, than bear the indignation of the Lord.

Some little time after I felt the concern of publishing the
little piece before mentioned revive with increased weight:
and after a time I believed it my duty to send it up to
the morning meeting of Friends in London,
for their inspection and judgment respecting printing it; which I did,
under the title of "`Reasons for leaving the national established mode of worship;
more particularly addressed to those who attend at the place called St.
Giles`'s Church Reading:`" accompanied with a few lines to the meeting,
from friends of our own, which the meeting with a few alterations approved of,
and left me at liberty to print it.
As soon as I received the pamphlets I sent one to the priest, with the following letter:
I also sent one to each of the principal professors with whom I had been acquainted.

[.embedded-content-document.letter]
--

[.letter-heading]
To * * * * *,

[.salutation]
Respected Friend;

"`The little Piece which this accompanieth, I think I can truly say,
I wrote under an apprehension of duty, uninfluenced by any personal motives whatever.
I submit it to thy candid perusal, and can assure thee,
that notwithstanding the apparent difference, I still retain an affectionate regard,
and a real respect for thee:
nor can I suppose thou wilt impute to a want thereof my omitting thy usual titles,
being persuaded thou art sensible that true honour and respect do not consist in words,
or any superficial expressions.
I was constrained to drop them,
from a belief of the inconsistency thereof with the simplicity of true Christianity,
and of the unlawfulness of feeding the vain mind in man, by giving him flattering titles.
I have desired to follow nothing by imitation, but from conviction,
and I hope these desires have been mercifully answered.

[.signed-section-closing]
I remain, respectfully, thy Friend,

[.signed-section-signature]
John Spalding

[.signed-section-context-close]
Reading 11 Mo. 1794

[.postscript]
Postscript: "`There is a little matter I have for some time
felt a desire to call thy serious attention to.
Not long since,
part of the goods of some of thy peaceable neighbours were taken away by force,
for the repairing, I apprehend,
the place where thy congregation meet to worship I have been led to consider
the inconsistency of this practice with the spirit of the gospel,
of which thou art esteemed a minister.
I have examined the Scriptures of Truth,
and do not find that either Christ or his apostles ever used, or taught such a practice,
to oblige those to support them, or their places of worship, who did not receive them.
__"`As ye would that men should do unto you,`"__ said our Lord,
__"`do ye even so unto them,`"__ for this
__"`is the law and the prophets,`"__
Now I am much inclined to think,
if thou wilt calmly and weightily consider this matter,
a deviation from this important injunction will appear.
If this people had the powers of the earth on their side (as thou hast in these
matters) and insisted upon thy helping to support their place of worship,
where thou hadst a conscientious objection to go, wouldst not thou think it unreasonable;
and rather that every society should support its own ministers and places of worship?
And truly there are those who from a real conscientious scruple,
cannot willingly uphold those called parish churches.
I have felt it myself, and expect I can if thou require it,
advance some weighty reasons for so doing;
at present my regard for thee induces me to press a serious examination of this matter;
and I feel a desire that customs originating in the times of ignorance and superstition,
and the more powerful motive of interest itself,
may not induce thee to contemn the simple, yet I hope sincere,
representations of the mean and despised.

"`Now this I do not write from any desire to avoid suffering for praised be the Lord,
there is a remnant at this day,
who are enabled to take joyfully the spoiling of their goods for a good conscience sake,
in supporting their testimonies against what they believe to
be repugnant to the spirit of the gospel dispensation.`"

--

[.offset]
This I sent with one of my pamphlets before-mentioned;
the next evening I received the following.

[.embedded-content-document.letter]
--

[.salutation]
Mr. Spalding,

"`As I am willing to hope that your pamphlet and letter were well meant,
I thank you for them; but as they are replete with most wicked errors,
and as the author of them is a schismatic and heretic,
I must reject both you and them.
As you once gave hope that you might walk in the ordinances of the Lord blameless,
and continue with us in a church which God is still filling with his glory,
I cannot but feel a regard for you,
and pity you the more for your departure and apostacy from the faith.
I would advise you to search God`'s word, and your own heart, with prayer,
for the teaching of his spirit, that you may discover the sound doctrine of the one,
and the sore plague of the other.
Peradventure God will give you repentance to the acknowledging the truth,
and you may be restored to a sound and sober mind, out of the snare of the devil,
by whom you are now taken captive at his will.
Should an event so desirable to yourself and your family ever take place,
I shall rejoice to salute and embrace you in Christ Jesus,
but till then I must beg to decline all correspondence with you.

[.signed-section-closing]
I am, Your sincere friend and well-wisher.

[.signed-section-context-close]
Reading, Nov. 28, 1794.

--

A little while after he desired my brother to tell me to send in his account,
and also to know if he should stop his tithes out of it, which amounted to three pounds.
I in consequence wrote his account, and sent it in the following letter,
with a little piece, called "`Reasons why the People called Quakers do not pay Tithes.`"

[.embedded-content-document.letter]
--

[.salutation]
"`Respected Friend,

"`I should not at this time thus communicate with thee,
but for thy inquiring of my brother somewhat respecting my paying tithes.
It appears to me thereby that thou art unacquainted
with our reasons for not paying tithes,
etc. yet, as I suppose from thy letter,
thou may not be willing to receive my reasons on that subject, I will only observe,
that it is not from any personal disregard to thee, nor in imitation of others,
that I refuse to pay them,
but from a full conviction of the inconsistency
thereof with the dispensation of the gospel;
and that if I did in any manner contribute to support such a practice,
it would be a denying that Christ is come, who by his coming put an end to,
and totally abrogated or disannulled, that law or dispensation to which tithes belonged.
I send thee a small piece on this subject.
Shouldst thou be disposed to be more fully informed respecting it,
I have other authors who have confuted every argument in favour of tithes,
etc. in this last and more glorious dispensation,

[.signed-section-closing]
I remain, respectfully, Thy Friend,

[.signed-section-signature]
John Spalding

[.signed-section-context-close]
Reading, 12 mo. 23d. 1794.

[.postscript]
"`P.S. As thou desired, I send thy account; and here it may be proper to remark,
that I cannot suffer thy demand to be paid thereby.
Thou, perhaps wilt think me troublesome and impertinent,
but the Lord knoweth my heart in this matter,
that it is from a persuasion of duty towards him
and not from a perverseness of disposition,
as men may suppose it is.`"

--

I found a spirit generally prevail among them, both preachers and hearers,
confident in their own opinion, and condemning without hearing the sentiments of others.
Oh! how doth my spirit mourn for them,
under a sense of the danger of their situation and a
persuasion of the applicableness of an ancient language,
"`The prophets prophesy falsely, the priests bear rule by their means,
and the people love to have it so; but what will they do in the end thereof!`"

Being appointed by the parish overseer this year,
I had frequent opportunities of observing the
difficulties many of the poor laboured under,
and was favoured to sympathize with them therein;
and I had often to consider the manner of living among these in superior situations,
as to outward things,
and it appeared to me inconsistent with the gracious designs of our heavenly Father,
that some should live luxuriously, and expend much upon superfluities,
while so many fellow-creatures were in want of the comforts and necessaries of life.
It seemed to me a great evil, and my spirit was often bowed in consideration thereof;
for I thought that the oppression of the poor, and the extravagant living of others,
was one cause of the judgments of the most High being at this
time so awfully executed in the neighbouring kingdoms.
And it was often the secret breathing of my spirit,
that the people of this land instead of applying to carnal weapons,
which was now pretty general throughout the kingdom,
and trusting to the multitude of their hosts,
might endeavour to avert the threatened indignation before it came home,
by turning every one from the evil of their ways,
to serve the Lord with their whole hearts, to relieve the distresses of the poor,
and content themselves with a moderate way of living, as becomes the followers of him,
who said, __"`My kingdom is not of this world.`"__

[.asterism]
'''

[.blurb]
=== A few serious queries and observations, addressed to the high professors of religion in this day, by one who was long in the profession, but knew not the power, till it pleased the Lord, by the ministry and writings of the people called Quakers, to direct him where alone the power is to be known, within.

What is a true Christian?
Is it one who assents to and believes certain facts, as recorded in holy writ,
and forms certain principles and opinions thereupon;
producing perhaps a partial reformation,
an abstaining from the grosser pollutions of sin,
but denying the possibility of a total cleansing and freedom from sin in this world?
Or is it one who knows not in word only, but in deed and in truth, a death unto sin,
and a new birth unto righteousness; a being born again, not of blood,
nor of the will of the flesh, nor of man, but of God?
"`For,`" says our blessed Lord,
"`except a man be born again, he cannot enter into the kingdom of God.`"
A man may know with Nicodemus, and confess, that Christ is a teacher sent from God,
he may be able to talk much about the doctrines of the gospel,
and fancy himself secure by imputation,
but what has this to do with the new birth so essentially necessary?
What can all his wisdom and understanding teach him.
Nay, he cannot come into the new birth till all is parted with.
The very nature of the thing implies a beginning again,
a life as different from his former as light from darkness.
"`Ye were sometimes darkness,`" says Paul, "`but now are ye light in the Lord.`"
Now he who knows this new birth, not a change of opinion,
not a comprehending the truths of the gospel in his understanding,
or joining this or that society, but who knows the thing itself; not the name,
not the imaginations concerning it, but the nature, the life, the essence;
will such a man be like what he was before?

The forerunner of our Lord expressly told his hearers,
when preparing them for the gospel dispensation,
"`The axe is laid to the root of the trees,
and every tree that bringeth not forth good fruit is hewn down and cast into the fire.`"
What tree and what root is there meant?
Is it outward or inward?
Who can answer that, but he who hath felt the axe, and the destruction,
in a measure of the corrupt tree?
"`His fan is in his hand, he adds, and he will thoroughly purge his floor;`"
(mark "`thoroughly,`") what will remain then?
O! that professors were concerned to know,
and willing to part with all that stands in the way,
that they may know indeed what it is to be thoroughly purged,
instead of denying the possibility of it;
for it is a dreadful thing to oppose or deny the power of Christ.

Christ said, "`Blessed are the pure in heart;`" but modern Christians,
as they would be thought, say, there is no purity of heart,
but it is and must remain deceitful above all things and desperately wicked?
Again it is said, "`who brings a clean thing out of an unclean?`"
That the heart is naturally unclean is allowed,
but hath not the Lord promised to cleanse his people from all their uncleanness,
mark all, what uncleanness will then remain?
Some attempt to excuse themselves by what Paul once experienced;
"`The flesh lusteth against the spirit, and the spirit against the flesh;
a law in the members warring against the law of the mind.`"
That Paul once felt that is allowed, but did he not after say,
"`There is no condemnation to them that are in Christ Jesus,
who walk not after the flesh but after the spirit;`" and did he not say,
"`The law of the spirit of life had made him free from the law of sin;
and how could they who were dead unto sin live any longer therein?`"
Doth he not again say, "`I am dead with Christ, nevertheless I live, yet not I,
(not natural sinful self,) but Christ liveth in me?`"
"`I will dwell in them and walk in them saith the Lord;`" and
will the Lord dwell in an unholy place?
As soon would light dwell with darkness.
Satan can indeed transform himself into an angel of light, yea, he, as God,
sitteth in the temple of God, shewing himself that he is God.
The imagining part in man is sure to be deceived,
and worship the appearance instead of the reality, for the world by wisdom,
man by his natural or humanly acquired abilities, knew not, nor ever can know God.
"`If any man, says Paul, will be wise, let him first become a fool,`"
that his old eye may be closed, and the new eye,
which alone can discern the things of God, may be opened.

Again, Christ saith,
"`Be ye perfect, even as your Father which is in heaven is perfect.`"
But modern Christians, as they call themselves,
say there is no such thing as perfection.
O that they would consider whom they oppose by so saying.

Doth not Paul desire those he was writing to,
to cleanse themselves from all filthiness of flesh and spirit,
perfecting holiness in the fear of the Lord;
and pray that others may be perfect and complete in all the will of God?
What does such plain express language mean?
O the subtlety of that serpent, who can reason and argue the true meaning away;
and O the lamentable estate of those that are so deceived by him,
who are sitting down at ease, with the vain imagination that what Christ hath done,
as they suppose for them, will be sufficient; without experiencing the work in them;
who having eyes see not, and ears hear not, in the true spiritual sense.

Again, Christ saith, "`Swear not at all;`" but modern Christians say,
We may swear in some cases.
We will reason about Christ`'s words, and judge ourselves what they mean;
how far they are to be obeyed or not.
Though James says, "`Above all things, my brethren, swear not.`"
Yet ye say, We may swear such and such oaths, O poor Christendom,
how is thy gold become dim!

Again, Christ saith,
"`Whosoever he be of you that forsaketh not all that he hath, he cannot be my disciple;`"
but now Christians can keep all; their own wisdom,
their own wills, the favour of the world, its riches and friendships,
its fashions and customs; though our Lord saith,
"`Whoever is the friend of the world, is the enemy of God;`" and Paul says,
"`If I yet please them, I am not the servant of Christ.`"
