[#ch-few-reasons.style-blurb, short="A Few Reasons for Leaving the National Worship"]
== A Few Reasons for Leaving the National Established Mode of Worship, Addressed principally to those who attend at the place called St. Giles`'s church, Reading.

[quote.scripture, , 1 Thess. 5:21]
____
Prove all things, hold fast that which is good.
____

[.salutation]
Friends,

My mind hath been much exercised at times, since I separated from your communion,
with desires for your real advancement in the spirit
and power of that religion you make profession of;
and being persuaded there are those among you who do really desire to know the truth,
I feel a renewed concern to salute these, in a degree I hope, of true gospel love;
and to offer to your serious consideration,
the reasons which induced me to separate from your society.
And truly, friends, there were many ties, which nearly united me to you;
and very unwilling I was for a considerable time,
to believe that those things I had been engaged in, and so highly esteemed,
were not what they had appeared to be; but, as I earnestly desired to know the truth,
whatever it might cost me, I felt the axe laid to the root of the tree,
and the fine buildings and plausible appearances were shaken.
I became sensible, that the tree must first be made good, before the fruit could be good;
a doctrine essentially different from what I had heard of men;
even of men highly esteemed; by whom I was taught,
that deliverance from sin is not to be expected in this life;
and was hearing day after day, the uniform acknowledgement of '`being miserable sinners,
having no health,`' etc. which I found,
by the manifestations of that spirit which
__"`is given to every man to profit withal,`"__ 1 Cor. 12:7,
and which discovers the secret things of darkness, to be not agreeable, but contrary,
to the scriptures of truth; which expressly declare,
that the great Author of the gospel dispensation
__"`came to save his people from their sins,`"__ Matt. 1:21,
and not in them: a very essential difference.
This I believed must be experimentally known,
feeling sin to be the great disease of the soul,
the alone cause of separation from the Most High, in whom alone true happiness is found.
I was sensible that while sin remained, the separation must continue, there being
__"`no communion between light and darkness, righteousness and unrighteousness;`"__ 2 Cor. 6:14,
nor could that gracious promise be fulfilled,
__"`I will dwell in them, and walk in them, I will be their God,
and they shall be my people;`"__ 2 Cor. 6:16, for the apostle says,
__"`ye are the temple of God, and the temple of God is holy.`"__ 1 Cor. 3:17.

Further, John the Baptist, who was sent to prepare the way of the Lord,
describing the nature and effects of his master`'s kingdom, says,
__"`Now__ (mark now) __is the axe laid to the root of the tree;
every tree that bringeth not forth good fruit,
is hewn down, and cast into the fire.__`" Matt. 3:10.
This is a language surely implying a complete,
effectual cleansing from all the pollutions of sin, even now in this life.
Our Lord himself uniformly, in all his discourses, inculcated this doctrine.
In that most excellent sermon on the Mount, Matt. 5:6.7,
he insists on the necessity of a righteousness superior to that of the law; for says he,
__"`except your righteousness exceed the righteousness of the Scribes and Pharisees,
ye shall in no case enter into the kingdom of heaven.`"__
What language can be plainer?
And that he did not mean an imaginary, merely imputed righteousness, as I fear,
many vainly suppose, is evident from the conclusion;
where he draws the comparison between those who hear, and do his sayings,
and them who hear, and do them not;
thereby fully establishing the possibility of doing them.
And if due attention is paid to every part of that discourse, I think it must be obvious,
that they who are of the happy number, who not only hear, but do those sayings,
and who our Lord likens to a building upon a rock,
on which they are able to withstand all opposition; will not be miserable sinners,
doing what they ought not to do, having no health in them;
etc. but will know a righteousness wrought in them far superior to that of the law.
For, as the law, the outward law, written on tables of stone,
took cognizance of outward actions; the law of Christ, written as the apostle says,
in the fleshly tables of the heart, reaches to the root, and source of action: for,
whereas the law said, __"`thou shalt not kill.`"__
Christ forbids being angry without cause.
Again, the law said, __"`Thou shalt not commit adultery;`"__
Christ forbids lust, thus striking at the root.
The cause being removed, the consequence or effect must unavoidably be done away.
Once more, the law said, __"`Thou shalt love thy neighbour, and hate thine enemy;
an eye for an eye, and a tooth for a tooth.`"__
Christ says,
__"`Resist not evil, love your enemies, do good to them that hate you;`"__
with much more of like import,
which many who profess to follow him, seem to pay very little attention to;
as though it was an indifferent matter, whether they do them or not.
But it may be well for such to consider whether our Lord would have said,
__"`Be ye perfect, even as your Father which is in heaven is perfect,`"__
if he did not mean they should be so;
and whether they who do as he there exhorts, will not be perfect.
I cannot conceive how it is possible to deduce any
other inference without grossly wresting the scripture.
__"`Ye are my friends,`"__ said he, at another time,
__"`if ye do whatsoever I have commanded you,`"__ John 15:14.
__"`He that loveth me keepeth my commandments,`"__ John 14:21.
__"`Not every one that saith unto me Lord, Lord,__
(that call me master and honour me with their lips),
__shall enter into the kingdom of heaven, but he that doeth the will of my Father,
which is in heaven,`"__ Matt. 7:21.
__"`If ye know these things happy are ye if he do them,`"__ John 13:17.
For if the simple belief of Christ`'s sufferings,
resurrection, etc. be sufficient to save; to what purpose was all his discourses,
wherein he repeatedly insists upon the necessity of regeneration, a being born again;
which certainly implies something more than a change of opinion,
a persuasion of the judgment, and a partial reformation.
For as he said to Nicodemus,
__"`That which is born of the flesh, is flesh and that which is born of the spirit,
is spirit,`"__ John 3:6.
it obviously follows,
that they who are really born of the spirit, will be of the same nature as the spirit.
Old things will be passed away, and all things become new, and all of God.
__"`A little leaven leaveneth the whole lump.`"__ Luke 13:21.
__"`New wine must be put into new bottles.`"__ Mark 2:22;
with many other similitudes, plainly implying the necessity of a total, effectual change.

Again to confirm this great and necessary truth, of freedom from sin,
he says to his disciples, __"`if ye continue in my word, then are ye my disciples indeed,
and ye shall know the truth, and the truth shall make you free,`"__ and,
to reprove their carnal ideas of a temporal outward freedom, he adds,
__"`He that committeth sin, is the servant of sin, and if the Son shall make you free,
ye shall be free indeed,`"__ John 8:31, etc.
That this freedom from sin, even from the power, as well as the guilt,
is to be known in this life, is certified again,
by his saying of those who die in their sins,
__"`Whither I go, ye cannot come,`"__ John 8:21.
Now if deliverance from sin is not known in this life,
we must of necessity die in our sins.
Therefore it matters not what knowledge a man hath, what is his faith,
or what profession he hath made, if he hath not known deliverance from sin.
This is a point so important, and a mistake therein liable to such baneful consequences,
that I am induced to dwell upon it, knowing from my own experience,
how prevailing is the contrary opinion.
Nor is it strange,
that people should prefer and indulge the notion of the possibility
of deliverance from the guilt and punishment of sin,
without the power thereof being subdued.
We naturally love ease, an ease which the cross of Christ is decidedly against.
So close does it apply, that it is, in our Lord`'s own words, as cutting off a right hand,
and plucking out a right eye. Matt. 6:29-30.
__"`Whosoever,`"__ says he, again and again,
__"`doth not bear his cross, and come after me, cannot be my disciple.`"__ Luke 14:27:
The apostle bears testimony to this important truth, where he says,
__"`They that are Christ`'s, have crucified the flesh with its affections and lusts.`"__ Gal. 5:24.
Surely if lusts and affections, the very root and seed of sin, are slain,
what can remain thereof?
In another place he says,
__"`How shall we, that are dead to sin, live any longer therein?`"__ Rom. 6:2.
Another apostle says, __"`Whosoever is born of God, doth not commit sin,
for his seed remaineth in him, and he cannot sin, because he is born of God.`"__ 1 John 3:9.

I have produced a few plain passages of scripture,
to shew the ground or cause of my separation; that deliverance from sin,
a being cleansed from all defilement thereof in this life, is not only possible,
but indispensably necessary; and that the contrary doctrine is fundamentally erroneous;
as it sets up the shadow instead of the substance, an imaginary, instead of a real,
holiness.
I may probably make some more observations on this most important point, as I proceed.
I shall now offer a few remarks on some of the services usually performed;
comparing them also with the scriptures of truth,
which most professors acknowledge to be the standard or rule;
from which comparison they clearly appear to me, not to be what many call them,
'`means of grace and ordinances of God; but the mere inventions of man,
set up in his own fallen wisdom, as a substitute for the life and power,
which were lost in a long dark night of apostacy: not the true worship of God,
but such bodily exercise as the apostle says,
__"`profiteth little,`"__ 1 Tim. 4:8.
For be it remembered,
the great Author of the gospel dispensation, expressly declared,
__"`that the true worshippers shall worship the Father in spirit and in truth.`"__ John 4:23.
And the apostle confirms it, by saying,
__"`We know not what we should pray for, as we ought;
but the spirit helpeth our infirmities,
and maketh intercession for us with groanings which cannot be uttered.`"__ Rom. 7:26.

Therefore, as this necessary assistance is not at our command,
for people to pretend to worship the Most High in a prescribed form,
or in the studied or extempore productions of their own natural or acquired abilities,
in their own wills, and their own time,
without waiting to feel the influences and movings of the Holy Spirit,
in and through which alone true worship can be performed, appears to me nothing better,
whatever it may be called, than will-worship.
The scriptures also repeatedly mention a growing in grace, 2 Pet. 3:18,
a going on unto perfection, Heb. 6:1.
How inconsistence then is the repeated uniform acknowledgement,
__"`We are miserable sinners, doing what we ought not to do, having no health in us?`"__ etc.
Doth it not obviously confess, if the truth is spoken,
that no benefit hath been received,
notwithstanding the frequent (as it is pretended) waiting upon the Lord?
But if it is true, as the scriptures declare,
that Christ came to '`save his people from their sins;`' they who make that confession,
acknowledge they are not of that number; for if they are miserable sinners,
they certainly are not saved from their sins,
however they may attempt to reconcile so plain a contradiction.
This is a language not confined to a particular part of the service;
the inconsistency of the whole appears equally obvious;
as at one time confessing their sins and wickednesses;
then called upon to address the most High, with pure, humble, penitent,
and obedient hearts; one while returning thanks for creation, preservation,
and redemption; again acknowledging having erred and strayed like lost sheep,
desiring to shew forth his praise not only with their lips, but in their lives,
by giving themselves up to his service,
and walking before him in holiness and righteousness all their days;
but still miserable sinners, doing what they ought not to do, etc.
Can this running backwards and forwards, one time saying one thing,
another time quite the contrary, be acceptable service to that God,
who searcheth the heart, trieth the reins, and requireth truth in the inward parts?
Again, in repeating the experiences of the royal Psalmist,
how is it possible but many gross falsehoods must be expressed?
For if the words of the mouth do not express the real experimental language of the heart,
however excellent they may be, yet they are to those who utter them,
not the language of truth but of falsehood.
I should hope a little serious consideration will convince of this.

Again, respecting the custom or practice of singing, I have a few observations to make.
How inconsistent it is,
that they who have just before been confessing their misery and wretchedness,
should appear so quickly and easily to forget all, and begin singing.
Surely it seems evidently to declare, they were not sincere in their acknowledgements,
or that they think it of very little consequence
whether their prayers are answered or not.
Besides, not only the manner to me appears absurd and inconsistent,
but the matter in many quite contrary to truth,
and to what has been just before openly avowed.
I could specify many instances in every collection I have seen,
but I wish people to search for themselves.
Surely this is trifling with serious things.
I am fully persuaded that the common practice of
singing is only calculated to amuse the creature,
to please the outward ear; whatever may be pretended of its warming the heart,
and kindling devotion.
And if those who practise it would be honest and candid,
I am of opinion they would be constrained to
acknowledge that amusement is the chief object:
or why so pleased with tunes and music?
Can it for a moment be supposed,
that the Almighty is to be pleased with such superficial conduct?
Surely not.
And with respect to its kindling devotion,
it may be well to remember what is said of those,
__"`who kindle a fire, and encompass themselves about with sparks;
they may walk in the light thereof, but they shall lie down in sorrow,`"__ Isa. 50:11.

I readily admit what is advanced to defend this custom, that our Lord and his disciples,
the night before he suffered, sang a hymn, but what or how we are not informed;
no doubt the matter and manner were both proper and seasonable; and that Paul and Silas,
in prison, "`sang praises to the Lord,`" I believe;
but I cannot conceive what argument can be deduced from thence
for the present custom of singing whatever may be given out,
suitable or not, whether praise, profession, acknowledgement, or petition.
I fully believe this outward inconsiderate singing is
very different from that recommended by the apostle,
__"`Singing with the spirit, and with the understanding.`"__ 1 Cor. 14:15.
__"`Singing and making melody in your hearts to the Lord,`"__ Eph. 5:19.
And I also believe, that the true source of praise,
even a grateful sense of the Lord`'s mercies can be more
consistently expressed than in outward jingle and sound.

Indeed, my friends, I fear you are, many of you, agreeably to your own confession,
in a miserable condition.
Suffer me to prevail upon you to consider,
whether your continuing year after year miserable sinners,
is not the consequence of your prayers not being heard:
and let a concern arise to enquire, whether you have been seeking aright or not:
for our Lord promised plainly and expressly,
__"`that they who seek shall find,`"__ Matt. 7:5.
Now, what have they found,
who continue as they acknowledge, '`miserable sinners having no health in them,`' etc?
Do they not rather confess that the means they have
used are insufficient to cleanse and heal them;
that they have not rightly applied to the great physician, to the balm of Gilead,
"`to that tree, whose leaves are for the healing of the nations;
but have been spending their money for that which is not bread,
and their labour for that which satisfieth not;
instead of hearkening diligently unto the Lord,
and eating that which is good;`" Isa. 55:2, that true bread of life,
which our Lord said, "`he that eateth of this Bread shall live forever?`" John 6:58.
It may be well to have recourse to these
means before the possibility of cure is denied;
lest they thereby deny the power of God,
that he is not able to "`cast out the strong man armed,
who keepeth his palace and his goods in peace,`" Luke 11:21. I think I need not add,
who is there meant by the strong man armed, where is his palace, and what are his goods.
The apostle speaks of some,
"`who had a form of godliness but denied the power thereof.`" 2 Tim. 3:5.
Now, it may be well to consider,
in what can the power of godliness be known, hut in dominion over its adversary,
which is sin.
And do not they who deny the possibility of sin`'s being subdued,
deny the power of godliness?
A serious consideration may not be unprofitable.

I have often admired, that those who plead for sin,
pretend highly to value the scriptures, and say,
'`the scriptures is the rule;`' whereas the scriptures
uniformly insist upon the necessity of holiness;
not an imaginary holiness, but a real purity of heart and of life.
"`Without holiness,`" said the apostle,
"`no man shall see the Lord,`" Heb. 12:14.
"`Be ye holy in all manner of conversation,
because it is written, be ye holy for I am holy.`" 1 Pet. 1:15.
"`Present your bodies, (mark, your bodies) a living sacrifice, holy,
acceptable unto God, which is your reasonable service.`" Rom. 12:1.
They talk much of the blood of Christ; it is a subject often in the mouth,
but what of the nature and effects of it is known,
let their own acknowledgements testify.
The apostle declares it cleanseth from all sin.`" 1 John 1:7.
Now how those who continue '`miserable sinners,
doing what they ought not to do,`' etc. can be cleansed from all sin,
let the considerate judge.

It is with me now, to answer some objections to this important truth;
and to remark on some passages of scripture,
which those who deny the possibility of sin being subdued,
endeavour to cover themselves with.
First, that '`The heart of man is deceitful above all things, and desperately wicked,
who can know it?`' Jer. 17:9.
That the heart of every man, of every natural unregenerate man,
is truly so, I firmly believe:
but be it remembered that the Lord promised to
give his people a new heart and a new spirit: Ezek. 36:26.
And dare any one say, that heart is deceitful and wicked?
O, beware of depreciating the gift of God.
"`Blessed are the pure in heart, saith our Lord, for they shall see God.`"
Matt. 5:8, "`A good tree cannot bring forth evil fruit,
neither can a corrupt tree bring forth good fruit.`" Mark 7:18.
"`The seed on the good ground are they who in an honest and good heart,
having heard the word, keep it, and bring forth fruit with patience.`" Luke 8:15.
For now, in the gospel dispensation,
the axe is laid to the root of the tree, Matt. 3:10.
What is the root of the tree there alluded to but the heart,
from whence words and actions have their birth?
"`Thou blind Pharisee,`" said Christ,
cleanse first that which is within the cup and the platter,
that the outside may be clean also "`Matt. 23:26.
And do they not in the stated form,
pray that God '`would cleanse the thoughts of their hearts,
by the inspiration of his holy spirit;`' a most excellent petition;
but what is it in those who use it, and yet deny the possibility of its being answered,
but a solemn mockery?
For if the thoughts of the heart are really cleansed, there can be no sin;
for sin defiles and pollutes the heart.

Another objection, is the language of the apostle,
where he speaks of "`a law in his members warring against the law of his mind,
and bringing him into captivity to the law of sin,
and that in his flesh dwelt no good thing,`" Rom. 7.
That the apostle once was in that state, I think, is beyond a doubt;
and that every real Christian experiences a similar,
till the strong man armed is cast out, and the old leaven purged away.
But that he was so at the time of writing it, to me appears by no means credible,
from what he has written just before and after; or he must grossly contradict himself,
which will hardly be allowed?
but rather that he was describing the effects of
the law upon the carnal unregenerate mind:
for he says, "`The law is spiritual, but I am carnal, sold under sin.`"
Now can it be supposed that the apostle was then carnal? etc.
Surely not, For just after, he says,
'`The carnal mind is enmity against God,`' and '`to be carnally minded is death,`' chap.
8:6,7. and that "`they who are in the flesh cannot please God;`" but he adds,
"`Ye are not in the flesh, but in the spirit, if the spirit of God dwell in you;
and if any man have not the spirit of Christ, he is none of his.`"
It consequently follows, that if the apostle was then in a carnal state,
he was none of Christ`'s, but at enmity against God.
A little before, he says, "`Knowing this, that our old man is crucified with him,
that the body of sin might be destroyed, that henceforth we should not serve sin:
for he that is dead is freed from sin,`" chap. 6:6,7.
And in the 2nd verse "`How shall we that are dead to sin, live any longer therein.`"
And in the 22nd verse, "`Being made free from sin, and become servants to God,
ye have your fruit unto holiness, and the end everlasting life.`"

Now let this plain language, both before and after, written no doubt at the same time,
determine whether the apostle was then in a carnal unregenerate state or not.
And though he elsewhere says,
"`Not as though I had already attained, either were already perfect;`" Phil. 3:10.
I think it in no respect favours the construction many put upon it,
that the apostle was then in a sinful state; but rather makes against them,
as it plainly condemns the notion,
of being perfectly and for ever justified by mere imputation,
and evinces the danger of sitting down at ease,
resting satisfied with an imaginary justification.
For in another place, speaking of the Christian progress, he says,
though he did not run as uncertainly, or fight as one that beateth the air,
yet he found it necessary to keep under his body and bring it into subjection,
or there was a danger, notwithstanding he had preached to others,
of his being still a cast away, 1 Cor. 9:6, 27.

Another objection is, the same apostle says, "`By grace ye are saved, through faith,
and that not of yourselves; it is the gift of God, not of works,
lest any man should boast.`" Eph. 2:8,9.
In answer to which,
I believe it is very necessary to distinguish between the works of man,
which he does in his own will and strength, and those works which are wrought of God.
Perhaps it is not rightly knowing this distinction that people cry out against works,
as though they were all self-righteousness.
The works of man, of the unrenewed carnal mind, yea the best of them, are as filthy rags;
but I think there should be a great care not to join the works of God
(those which he worketh in his people) with man`'s own works;
for in the next verse the apostle says,
"`Ye are his workmanship,
created in Christ Jesus unto good works, which God hath before ordained,
that we should walk in them.`"
That it is by grace, I believe, no real Christian will deny, but will,
with humble gratitude in all his progress, acknowledge with the apostle,
"`by the grace of God I am what I am,`" 1 Cor. 15:10.
This grace the same apostle declared,
hath appeared to all men, (mark that, not to any particular part) and teaches,
that denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly, in this present world.
He does not say (it teaches) we must continue in sin, "`What,`" says he in another place,
"`shall we continue in sin, that grace may abound, God forbid,`" Rom. 6:1.
That it is also through faith, who will deny?
for "`without faith it is impossible to pleased God,`" Heb. 11:6.
But the apostle speaks of a dead faith, James 2:17.
of a faith the devils have, verse 19. The true faith, he says,
worketh by love, Gal. 5:6. purifieth the heart, Acts 15:9.
and overcometh the world, 1 John 5:4.
Now what faith have those, who say,
they are '`tied and bound with the chain of their sins,
that they are miserable sinners having no health in them,`' etc.
The tree is known by it fruit.

Again, the words of our Lord, when upon the earth in the days of his flesh,
to those whom he had healed of their diseases,
are pleaded in excuse for continuing in sin,
as "`Thy faith hath saved thee, thy faith hath made thee whole,`" etc.
But be it remembered, that those to whom he said so were completely cured,
received '`perfect soundness;`' and I believe, there is a remnant at this day,
who witness the same works,
spiritually accomplished by the powerful operation of the same word in the heart,
even a being made whole, a being healed of the great disease of sin,
prefigured by the various cures performed on the bodies of the people.

Once more, another argument adduced is where the apostle says,
"`If we say we have no sin we deceive ourselves and the truth is not in us,`" 1 John 1:8.
But a due attention to what follows,
I think will clearly explain,
that the apostle does not favour the idea that he was then in that state; for he adds,
"`if we say we have not sinned,`" plainly alluding to time past, and continues,
"`if we confess our sins, he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness;`"
and as all unrighteousness is sin, chap. 5:17.
they who are cleansed from all, surely can have none remaining.
It is the sincere desire of my mind, that the people would consider for themselves,
and not take things of such importance upon trust,
but attend to the advice of the apostle,
"`Let every man prove his own work,
then shall he have rejoicing in himself, and not in another,
for every man shall bear his own burden.`" Gal. 6:4-5.
"`Be not deceived,`" he adds just after,
"`God is not mocked; whatsoever a man soweth, that shall he reap,`"
whatever be his opinion, knowledge or faith.
And in another place he says, though he had all knowledge,
could understand all mysteries, though he had all faith, even to remove mountains,
yet he might be as nothing, 1 Cor. 13:2.

Therefore it might be well to have a care of talking so highly of the scriptures,
while the life and conversation is not agreeable thereto;
and remember the words of our Lord to some of old,
"`Search the scriptures for in them ye think ye have eternal life;
and they are they which testify of me,
and ye will not come unto me that ye might have life,`" John 5:39-40.
From which it appears,
and is worthy of the most serious attention,
that those who had the scriptures and valued them,
as to think they had eternal life in them, yet they would not come unto Christ,
of whom they testified;
and "`who was and is alone the life as well as the light of men,`" John 1:4.
Therefore it may be well to take care of putting the letter,
the testimony, the declaration, concerning an object, for the object itself;
for our Lord did not say the scriptures is the way; but
"`I am the way, the truth, and the life, and no man cometh unto the Father but by me,`" John 14:6.
And learn the difference between the letter,
the outward word, and the word that was in the beginning, John 1:1,
before the scriptures, "`the word nigh in the mouth, and in the heart;`" Rom. 10:8,
"`which is quick and powerful, sharper than a two-edged sword,
dividing asunder soul and spirit, joints and marrow,
and is a discerner of the thoughts and intents of the heart,
before whom all things are naked and open,`" Heb. 4:12;
and of whom, as I before observed, the scriptures testify;
and without whose all-powerful aid they remain a dead letter, a sealed book.
The apostle declared, the things of God can only be known by the Spirit of God, 1 Cor. 2:11.
They are foolishness to the natural man.
Therefore I think we should be careful how we attempt to comprehend the truths,
which are contained in the scriptures by our own understandings; but rather be willing,
as the apostle recommends, to become fools, that we may be truly wise, 1 Cor. 3:18.

[.offset]
I would now offer a few remarks on those two ordinances or ceremonies,
Baptism and the Lord`'s Supper as they are called.

With respect to the first, as practised by those I more particularly address myself to,
little need be said; as sprinkling infants is not even an imitation of true baptism,
has no relation to it whatever,
nor do I believe there can be found a single precept or
example for it in any of the scriptures of truth.
I am well persuaded it is,
like many other things of the kind, a mere popish invention,
in the times of darkness and apostacy, as a substitute for the reality;
not in any one respect calculated to answer any good purpose whatever.
It may be well seriously to consider a language used at that ceremony,
"`that this child is regenerate, and grafted into the body of Christ`'s church;`"
and in the catechism respecting it, that
"`he is therein made a member of Christ, a child of God,
and an inheritor of the kingdom of Heaven.`"
Now let every considerate person solemnly ask himself,
whether he really believes such effects are really produced by it.
If it is possible that any one can think so, his ideas of regeneration,
and Christ`'s church also, differ very widely from mine.

Let it be considered also, what people are taught to promise at this ceremony:
"`To renounce the devil and all his works, the pomps and vanities of this wicked world,
and all the sinful lusts of the flesh; to keep God`'s holy will and commandments,
and to walk in the same all the days of their lives.`"
Are they not here required to promise what is believed
and confessed to be impossible to perform?
for surely if it was performed, they would not be
"`miserable sinners, doing what they ought not to do,`" etc.

That baptism is necessary, absolutely necessary, for every member of Christ`'s church,
I fully believe; but I believe, no application of water, even when rightly imitated,
is the one true baptism.
It is not the putting away the filth of the flesh,
which is all outward elementary water can do,
but "`the baptism of the Holy Ghost and of fire,`" Matt. 3:11,
even a being baptised in the name, that is nature, of the Father, Son, and Holy Ghost;
thereby experiencing the consuming of the earthly part in themselves,
and a being cleansed and purified from all filthiness of flesh and spirit,
perfecting holiness in the fear of the Lord; for the apostle says,
"`As many as are baptized into Christ, have put on Christ,`" Gal. 3:27,
not imaginarily, but really; and being buried with him,
by this spiritual baptism into death, even a death unto sin:
that "`like as Christ was raised from the dead by the glory of the Father,
so they also will walk in the newness of life,`" Rom. 6:4. And again,
If any man be in Christ he is a new creature, old things are passed away,
all things become new, and all of God.`"
2 Cor. 5:17, and if all of God, there can be no sin,
for "`sin is of the devil, and not of God.`" 1 John 3:8.

With respect to that other ceremony, called the Lord`'s Supper,
notwithstanding I am sensible of the deep rooted prejudice in favour of it,
I feel no discouragement; under a belief that a glorious day is dawning,
when clouds and shadows, signs and appearances, shall give place to reality,
to the pure essential substance.
I am perfectly satisfied in mine own mind respecting it,
and will endeavour to give my reasons,
why I believe it is not of that consequence or obligation many fix upon it.

That our Lord, the night before he suffered, took bread and brake it,
and gave to his disciples, as also the cup, I believe; and that he said,
this do in remembrance of me; but that he enjoined it to be an ordinance I cannot find.
I presume it will be allowed to be a part of the feast of the Jewish passover,
as our Lord said,
"`With desire, I have desired to eat this passover with you, before I suffer,`" Luke 22:16.
and which was a remarkable type or figure of Christ,
who was the very Paschal Lamb, the substance or antitype itself.
That the bread and wine, as a part of the passover,
represented the body and blood of Christ,
to be broken and shed for the remission of sins, I presume will also be allowed.
Now as there is certainly a very essential difference
between the sign and the thing signified,
let us consider a little, which is of most consequence,
or whether both are of obligation.
I expect none to whom I address myself will deny,
that Christ was and is really the substance and antitype of every type and figure,
under the Mosaic ceremonial dispensation.
This then being one of those figures representing the death of Christ;
the substance being come, the type fulfilled, what need of the shadow;
why not give place, as others are acknowledged to do?
The apostle, writing to some, remarks, "`As often as ye eat this bread,
and drink this cup, ye do shew the Lord`'s death, till he come.`" 1 Cor. 11:26.
But this I think,
by no means implies that it was an enjoined ordinance, but rather,
that those to whom he was writing,
continued in the use or observance of the jewish passover.
This I think, cannot appear improbable, when it is considered,
that for a time it was taught by some of the disciples,
that "`it was needful to be circumcised, and to keep the law of Moses,`" Acts 15:5.
of course this among the rest.
Therefore it appears to me, that they, as yet, knew not, in a spiritual sense,
the coming of Christ; that is, his spiritual appearance in their hearts;
an inference which seems to be confirmed by what is recorded of some,
who had been baptised with John`'s baptism, that is of water,
yet had not so much as heard whether there were an Holy Ghost, Acts 19:2.
the promised mode of his coming again, John 16:7.

Again, the apostle says, speaking unto wise men, no doubt spiritually wise,
"`The cup of blessing we bless, is it not the communion of the blood of Christ:
The bread we break, is it not the communion of the body of Christ?`" 1 Cor. 10:15,16.
Can it be supposed that he here alludes to outward bread and wine?
for if he did, all who partake of that ceremony, let them be who they may,
or what they may, have communion with Christ.
Surely that would be joining light and darkness, Christ and Belial,
righteousness and unrighteousness together,
in direct opposition to the same apostle`'s plain declaration to the same people. 2 Cor. 6:15.
He says again,
"`Ye cannot drink of the cup of the Lord, and the cup of devils;
ye cannot be partakers of the Lord`'s table and the table of devils,`" 1 Cor. 10:20.
Now it is very obvious,
that any can partake of the outward bread and wine,
therefore that cannot be the cup and table of the Lord.
Again, what is recorded of the disciples breaking bread from house to house, Acts 2:24,
I think by no means implies such a ceremony,
but rather a social way of living among themselves; as it is said,
they had all things common, verse 44, and, from what immediately follows,
"`did eat their meat with gladness and singleness of heart,`" verse 46,
plainly alluding to their common meals.
It is also I think, very observable, that when the apostles were assembled at Jerusalem,
to consider what was necessary to be enjoined to the believing Gentiles,
this ceremony was not even mentioned: which had it been necessary,
would sure not have been omitted, considering the things which were then enjoined;
most of which have since been laid aside, Acts 15:20.
But our Lord`'s own words appear to me decidedly to discountenance the outward sign;
as where he emphatically calls himself the "`Bread of Life.`"
"`That his flesh is meat indeed, and his blood drink indeed,
and that whosoever ate and drank it had eternal life.`" John 6:46, etc.
And to reprove their carnal ideas of outward eating and drinking, verse 52,
and to direct their minds to the spiritual allusion, he adds,
"`What, and if you shall see the Son of Man ascend up where he was before,`" verse 62,
how will ye eat him then?
not in outward bread and wine,
"`it is the spirit that quickeneth, the flesh (or outward food) profiteth nothing.`"

I believe there are among those whom I address myself to,
such as are sensible of the necessity of this spiritual communion,
and are truly desirous to partake thereof.
Far be it from me to wound any of these.
I do tenderly salute them,
and feel a degree of unity with the least appearance of the true seed of the kingdom:
I would not hurt the least plant of the Lord`'s own right hand planting.
However some little differences may appear,
yet let me say to these in a spirit of love and unity,
as this is acknowledged to be but a sign or token, why is this continued,
when others of equal authority and obligation are dispensed with?
For instance, that of circumcision, which our Lord submitted to, Luke 2:21;
and which for a time, even after his ascension, was enjoined by his disciples,
as I before quoted; Why this laid aside?
It may perhaps be answered, this sign according to the apostle`'s definition of it,
represented the circumcision made without hands,
in putting off the body of the sins of the flesh, Col. 2:11.
I fully believe it did,
and as it is equally true, that bread and wine is also a sign,
there appears to me not a shadow of a reason,
why the one should be continued in preference to the other:
the thing signified by both being of equal obligation.

Again, it is worthy of observation, that the beloved disciple John, in his relation,
makes not the least mention of this ceremony;
but is very particular in giving an account of our Lord`'s washing his disciples feet.
Why is not this ceremony observed,
as it appears to be more particularly enjoined than the other?
For says Christ, "`Ye call me Master, and Lord, and ye say well, for so I am;
if I then your Lord and Master have washed your feet,
ye ought also to wash one another`'s feet, for I have given you an example,
that ye should do as I have done unto you,`" John 13:3.
Now where can there be found so strong an injunction for the other,
that of bread and wine?
If it is answered, that was a sign or figure to teach humility and love to each other,
which I readily admit it was,
I think it is necessary to prove the other to be somewhat more
than a sign to support its continuance in preference,
which I expect will hardly be attempted.
That it was not practised or observed as an ordinance by the apostles,
I think evidently appears, from the whole tenor of their writings.
Paul reproves some for being subject to ordinances.
"`Touch not, taste not, handle not,`" says he, "`which all are to perish with the using.`"
Col. 2:20, and doth not outward bread and wine perish with the using?
The apostle well knew the true living bread was not of a perishable nature.
Again, he says, "`Let no man judge you in meat and in drink,
or in respect to the holy day, new moon, or the sabbath, which`" he adds,
"`are a shadow of things to come, but the body, (the substance) is of Christ,`" verse 16.
In another place he says,
"`The kingdom of God is not meat and drink, but righteousness and peace,
and joy in the Holy Ghost.`" Rom. 14:17.
And to some others he said
"`I am afraid of you, lest I have bestowed on you labour in vain;`"
because after they had known God,
had tasted somewhat of the substance,
they turned again to the weak and beggarly elements,
whereunto they desired again to be in bondage. Gal. 4:9.
"`Ye observe days, and months, and times, and years,`" verse 10, said he,
which he had declared to be but shadows of good things;
and I fear the same language is too applicable to many,
who make a very high profession in this day.

From what I have observed on this subject, I think to an unprejudiced mind,
it must appear that the true supper of the Lord is an inward, spiritual communion.
"`Behold,`" says Christ, "`I stand at the door, and knock:
if any man hear my voice and open the door, I will come in to him, and will sup with him,
and he with me.`" Rev. 3:20;
and that the outward bread and wine,
was nothing more than a part of the Jewish ceremonial dispensation; neither commanded to,
nor practised generally by, the gentiles in the apostle`'s days.
For, I would just add, if it is a necessary ordinance; if in other words,
it is what by many it is asserted to be, the effects of it would be evident;
for our Lord said, "`Whosoever ate his flesh and drank his blood, had eternal life.`"
Now I presume no one to whom I now address myself will
impute such an effect to outward bread and wine;
therefore it cannot be the Lord`'s supper.
We no where read of two suppers.
The difference between the sign and thing signified, the shadow and the substance,
I believe many are in a degree sensible of; and as the substance,
the reality is to be partaken of, yea absolutely necessary; (for said our Lord,
"`Except ye eat the flesh of the Son of Man and drink his blood,
ye have no life in you;`" John 6:53) and as I before observed,
we read of but one supper of the Lord;
surely it is of consequence rightly to know which is indeed the true supper.

I have no doubt but there are those who in sincerity and
uprightness of heart continue in the use of the sign;
far be it from me to judge these.
I have only a caution to give in love, that where these signs are regarded,
it may be as to the Lord, and not unto men.
See Rom. 14:6. I fully believe religion doth not consist in observing,
or not observing, outward ceremonies.
For as the apostle says, "`In Christ Jesus, neither circumcision availeth any thing,
nor uncircumcision; but a new creature;`" Gal. 6:15.
It is not a name, a profession, or any outward observance;
but I am not without a fear that many regard them as to men,
and are in bondage unto them, and so settled down at ease in them,
that they will hardly hear the least objection to them.
Such perhaps must be left for a time: however,
I have given some of my reasons for absenting myself from your communion,
and why I believe the worship there performed,
is not the worship which the Lord requireth; that it is not agreeable,
but contrary to the Scriptures; that it is not '`the means of grace,
and ordinance of God,`' but the invention and imagination of man;
that it is wrong in principle and in practice; in _principle,_
because you are taught you must not expect deliverance from sin in this life,
whereas the scriptures testify the contrary; in _practice,_
because you worship in your own wills, and teach for doctrines the commandments of men,
which our Lord testified against; Mark 7:7;
yea, in an unregenerate state,
according to your own confession, for a sinner is not regenerate.
Therefore, what I have heard among you, that your best services are polluted,
is strictly true; for while you yourselves are in the polluted state,
all your performances are polluted also.
"`For who can bring a clean thing out of an unclean? not one,`" Job 14:4;
but it may be well to remember, it stands an unchangeable truth,
"`That the sacrifices of the wicked are an abomination to the Lord,`" Prov. 21:27;
and though we may amuse ourselves with the vain idea that all is well,
I do assuredly believe, that to offer any acceptable sacrifice or service, we must know,
experimentally know, a being washed, sanctified,
and justified in the name of the Lord Jesus, and by the spirit of our God. 1 Cor. 6:11.

Therefore remember a language of old to some who had no health in them,
but were unsound from head to foot, as many confess they now are.
"`To what purpose is the multitude of your sacrifices?`" Isa. 1: 11.
"`Bring no more vain oblations, incense is abomination to me,
the new moons and sabbaths, the calling of assemblies I cannot away with,
it is iniquity even the solemn meeting.
When you spread forth your hands, I will hide mine eyes, yea, when ye make many prayers,
I will not hear.`" ver. 13, 14.
And consider the exhortation to them, "`Wash ye, make ye clean,
put away the evil of your doings from before mine eyes: cease to do evil,
learn to do well,`" etc. ver. 16.
Then it is added, "`Though your sins be as scarlet,
they shall be as white as snow: though they be red like crimson, they shall be as wool.
If ye be willing and obedient, ye shall eat the good of the land;
but if ye refuse and rebel, ye shall be devoured with the sword:
for the mouth of the Lord hath spoken it.`" ver. 18.
Oh, how awful is this denunciation now fulfilling around us!
It is the fervent breathing of my spirit, that this highly professing,
much favoured nation, who have been calling abundantly upon the Lord with their mouths,
and honouring him with their lips, may avert the impending stroke,
by truly humbling themselves before him; and as his judgments are in the earth,
may indeed learn righteousness, Isa. 26:9.

I know, friends, from a degree of experience,
that there are many and various appearances, signs, and shadows,
set up among professing Christians; some of which I have pointed out.
I now wish to direct, according to the ability I am at present favoured with,
to the reality or substance itself;
and this inestimable treasure which I had long in vain sought for without,
among the various appearances, I at last found to be within.
I can anticipate the surprise, and perhaps the indignation,
the word _within_ may excite in some minds, who may be ready to exclaim,
Can there be any good thing in man?
Yes, friends, the sovereign good, the only good, is to be found there;
and I desire your patient attention while I endeavour to remove that unjust, delusive,
yea too destructive idea, that nothing good is to be found in man.

I believe it is the grand artifice,
the most successful insinuation of the great adversary of mankind,
to divert the attention from that which is alone able
effectually to destroy his kingdom or rule in the heart,
and draw it to objects without, to similitudes and appearances.
(Mystery Babylon.)
This good then, though in man, is not of man,
it is not natural to him; but a free, spontaneous, unmerited gift.
This good is, with reverence be it spoken, even God himself; a truth,
I believe of the utmost importance to be experimentally known by every individual;
and a truth abundantly testified to in the sacred writings; as the ground work,
the substance, the foundation of real religion;
a language also repeatedly expressed by the professors of Christianity; though the truth,
the reality of it, appears so little known, as by many even to be denied.
Do not you frequently read,
"`I will dwell in them, and walk in them; I will be their God,
and they shall be my people,`" 2 Cor. 6:16.
"`If a man love me,`" said our Lord,
"`he will keep my words, and my Father will love him, and we will come unto him,
and make our abode with him,`" John 14:23.
"`The Comforter, even the Spirit of Truth,`" proceeding from the Father,
said he, "`dwelleth with you, and shall be in you,`" ver. 17.
"`Know ye not,`" said the Apostle,
"`that Jesus Christ is in you except ye be reprobates?`"
2 Cor. 13:5, and that your bodies are the temples of the living God? 1 Cor. 6:19.

I could multiply quotations of Scriptures, to prove this great important truth,
but am sensible that those to whom I address myself are well acquainted with the words.
You are frequently reading, of "`Christ within the hope of glory,`" Col. 1:27,
under various similitudes; but what is the reason, he is not known there?
It is an important question.
What is the reason, I again repeat it,
that Christ so often read of in the Scriptures as within,
notwithstanding so much talk and imaginations about him, is not known there in reality?
I believe, friends, I can tell you the reason why he, the one great foundation,
is not known, where alone he is truly to be known.
Because he is not sought for there; but in something without,
some appearance or representation of him, a knowledge gathered from men or books,
from the history or outward letter, which, however highly it may be valued,
I believe is merely notional.
The real experimental knowledge is only known by his internal appearance,
his second coming, without sin, unto salvation; Heb. 9:28.
and the operation and effects thereby produced.
See Mal. 3:3, "`The kingdom of God,`" said our Lord,
"`cometh not by observation:`" man with all his wisdom, is unable to comprehend it,
neither shall they say, "`Lo here is Christ,
or lo there,`" not in any outward appearance,
"`for behold the kingdom of God is within you.`" Luke 17:20-21.
"`Say not in thine heart,`" said the apostle,
"`who shall ascend into heaven that is to bring Christ down from above,
or who shall descend into the deep,
that is to bring Christ again from the dead:`" He is not at a distance,
but "`the word is nigh thee, in thy mouth and in thy heart,`" Rom. 10:6-8.

Our Lord represented this great truth by various objects or similitudes,
to convey spiritual instruction to his disciples; as a treasure hid in a field;
Matt. 13:44, seed sown in the ground; Mark 4:26, a grain of mustard seed;
Matt. 13:31, a little leaven hid in meal; ver. 33,
plainly alluding to this inestimable treasure as hid in the heart,
the earthly part of man.
There were some of whom our Lord said, having ears they heard not;
they could not understand the spiritual meaning of his parables; but to some he said,
"`Unto you it is given to know the mysteries of the kingdom of God.`" Mark 4:11.
Now, friends, it is of consequence to know of which number we are,
whether these are still to us as parables,
or whether we know that which unfolds their true meaning:
"`I am the light of the world;`" said Christ,
"`he that followeth me, shall not walk in darkness, but shall have the light of life.`"
John 8:12.

The apostle says there is no communion between light and darkness. 2 Cor. 6:14.
If we have not light, we must of necessity be in darkness.
There is a spiritual light, as well as a natural.
This great apostle to the gentiles, declaring his commission to preach the gospel,
said it was to turn people from darkness to light,
from the power of satan unto God. Acts 26:18.
Of what consequence then is it to be acquainted with this light,
by which alone we can discern between good and evil.
"`All things,`" said the apostle
"`that are reproved, are made manifest by the light; for whatsoever doth make manifest is light.`"
Eph. 5:13.
That we may know what this light is the scriptures abundantly declare,
John the Baptist was sent to bear witness of this light, which is the true light,
which lighteth every man that cometh into the world. John 1:8,9.
In him, i. e. Christ, was life, and the life was the light of men. ver. 4.
This light shineth in darkness, even the dark heart of man;
though the darkness comprehended it not. ver. 5.
This is the light of the glorious gospel; therefore, friends,
I caution you to beware of calling it a natural light, or a new light as many have done.
For I believe the same light, if attended to and its discoveries obeyed,
will effect the same works spiritually in the heart, or inner man,
as it formerly did on the bodies of the people.
Therefore I believe there is great danger of speaking evil of the light, for whoever do,
confess they are strangers to it, and of course are walking in darkness,
for there is but one true spiritual light.
And "`If we say we have fellowship with him and walk in darkness, we lie,
and do not the truth: but if we walk in the light, as he is in the light,
we have fellowship one with another, and the blood of Jesus Christ his Son,
cleanseth us from all sin.`" 1 John 1:6-7.

Our Lord himself plainly declared that "`Every one that doeth evil, hateth the light,
neither cometh to the light, lest his deeds should be reproved;
but he that doeth truth cometh to the light, that his deeds may be made manifest,
that they are wrought in God.`" John 3:20-21.
Therefore it is not strange that those who plead for sin, which is evil,
should speak against this light, and call it a natural light; or any thing,
to excuse themselves; because it cannot but condemn them.
Those things which the light, if attended to, would manifest to be evil,
are too dearly loved to be parted with,
while they can persuade themselves they are secure in retaining them.
I speak from experience, and do earnestly recommend a turning to this light within,
from all the __'`Lo heres,`'__ and __'`Lo theres;`'__
the various appearances, signs, and shadows,
set up by the will and wisdom of men, in the times of darkness and apostacy;
even to Christ within, the hope of glory, the true foundation, 1 Cor. 3:11;
the rock against which as it is faithfully abode in,
even the gates of hell shall not prevail, Matt. 16:18; nor all the opposition of men.
This I believe is the substance of every shadow, the reality of every appearance,
the word nigh in the mouth and in the heart; the true anointing,
which is truth and no lie,
and which teacheth all things without need of man`'s teaching. 1 John 2:27.
This is the new covenant, graciously promised by the Most High.
"`I will put my law in their inward parts, and write it in their hearts,
and will be their God, and they shall be my people;
and they shall teach no more every man his neighbour, and every man his brother, saying,
Know the Lord, for they shall all know me,
from the least of them unto the greatest of them, saith the Lord.`"
Jer. 31:33,34.

Behold said our Lord, the kingdom of God is within you. Luke 17:21.
The seed of the kingdom which is sown in the heart,
though too small for the eye of man`'s wisdom to discover,
though it is still to the high professing Jew a stumbling block,
and to the worldly wise Greek foolishness;
yet it is to those who hear its call and obey it, Christ the power of God,
and the wisdom of God. 1 Cor. 1:23-24.
This I believe is the new birth,
without which our Lord declared no one even could see the kingdom of God. John 3:3.
The birth which is not of blood, nor of the will of the flesh,
nor of the will of man, but of God, John 1:13.
For that which is born of the flesh,
however high and specious its appearance, is still flesh;
and that which is born of the spirit,
however mean and contemptible in the eye of man`'s wisdom, is spirit.
The gospel is a spiritual dispensation.
The spirit of truth inwardly manifested, our Lord promised should guide into all truth. John 16:13.
The apostles were not to leave Jerusalem till they had received it,
Acts 1:4, and then we are informed,
"`They spake as the spirit gave them utterance.`" Acts 2:4.
We have no reason to suppose they used any form of words,
neither that they spake when or where they chose;
but we are frequently informed of their going or forbearing,
as by the spirit they were directed; Acts 8:29; 19:7,
etc. neither are we to suppose that this influence and
direction of the spirit was confined to any period of time;
for, says our Lord,
"`Lo, I am with you always, even unto the end of the world.`" Matt. 28:20.
What a departure from their example and precepts is
lamentably conspicuous among most professing Christians;
who have invented various images, forms, and modes of worship,
which they can perform when they please;
evidently acknowledging that they think the influence
and assistance of the spirit unnecessary;
at least that they will begin at a venture, whether it may come or not!
Surely it may be well to consider,
whether it is not offering strange sire before the Lord. Lev. 10:1.
The only true worship under the gospel dispensation, is,
agreeably to our Lord`'s express declaration, that which is in spirit and in truth,
John 4:24, and as the influences and movings of the spirit,
(although so absolutely necessary,
as that no acceptable worship can be performed without them) are not at our command;
how proper, yea, how needful then, is an humble, silent, dependent waiting upon Him,
who alone can administer this assistance;
that thereby the true preparation of the heart may be experienced,
to receive whatever He, who searcheth the heart,
and who alone knoweth what is good for those who wait upon him,
may be pleased to administer: whether immediately,
by his still small voice in the secret of the heart; or instrumentally,
by whomsoever he may please to appoint!

"`They that wait upon the Lord,`" said the Prophet,
"`shall renew their strength.`" Isa. 40:31.
It is the professed object of most assemblies for religious worship,
to wait upon the Lord.
Now, whether those who in solemn humble silence,
wait to feel the influences of the spirit, to instruct and enable,
when and what to offer, or what immediately to receive from the fountain of good,
are such as that promise applies to; or those who are always ready to begin,
either in a prescribed form,
or in the exercise of their own natural or acquired abilities,
whether they may have the assistance so necessary or not;
I think a little serious consideration may determine.
Indeed the plain express meaning of the term, _Waiting,_ appears to me to be a silent,
attentive expectation of something; and if it is weightily considered, that,
at such times, we more particularly profess to approach the sacred presence of Him
"`who searcheth the heart, trieth the reins, and requireth truth in the inward parts;`"
who cannot possibly be deceived
or amused by the most plausible expressions or the most eloquent language;
who has decidedly condemned the practice of drawing near to him with the mouth,
and honouring him with the lips, whilst the heart is far from him; Isa. 29:13,
surely it is needful at such times to wait, silently wait,
for the reception of spiritual power,
lest we should be like those who offer the sacrifice of fools. Eccles. 5:1.
"`Let not thine heart,`" said the wise man,
"`be hasty to utter any thing before God, for God is in heaven and thou upon earth;
therefore let thy words be few.`" ver. 2.
"`Without me,`" said our blessed Lord, "`ye can do nothing.`" John 15:5.

Yet the practice of many who profess to follow him,
evidently declares that they think they can do without him, for they are,
as to words and outward performances, always ready.
The apostle plainly declared, that "`we know not what we should pray for as we ought,
but it is the spirit that helpeth our infirmities.`" Rom. 8:26.
Then what are all the arts of composition,
and the powers of human eloquence, without this assistance,
but as "`sounding brass or a tinkling cymbal?`"
"`When ye pray,`" said our Lord, "`use not vain repititions as the heathen do;
for they think they shall be heard, for their much speaking:`" Matt. 6:7,
a language too applicable, I fear, not only to the prescribed formal prayers,
but to the more private extempore productions,
as though prayer consisted in outward expression;
an idea repeatedly condemned in the Scriptures of Truth.

The apostle, after saying we know not what to pray for, adds,
"`The spirit itself maketh intercession for us,
with groanings which cannot be uttered,`" and Christ
called them hypocrites who prayed to be seen of men;
Matt. 6:5, and directed his disciples to pray in secret to the father;
who seeth in secret. ver. 6.
The apostle also recommends a praying always,
with all prayer and supplication in the spirit,
and watching thereunto with all perseverance. Eph. 6:18.
He does not recommend to begin singing as soon as they conclude a prayer.
In another place, he exhorts to a "`Continuing instant in prayer;`" Rom. 12:12,
again, "`Pray without ceasing;`" 1 Thess. 5:17
from all which I think it must appear
__that there may be true prayer without words,
and that there may also be words without prayer.__
I believe there are those possessed of considerable abilities, a ready flow of words,
and a pleasing eloquent delivery, who can at any time when they please,
deliver what I have heard called an excellent prayer;
without waiting to feel that influence, which can alone enable to
"`pray with the spirit, and with true understanding;`"
but though such exercises may produce a temporary warmth,
both in speaker and hearer, I believe,
it will be found to be only a fire of their own kindling, a mere appearance,
and not the effects of the live coal from the true altar. Isa. 6:6.
The same observations are equally applicable to
every other external performance of worship,
public or private: for however it may affect the outward ear, yea, and kindle sparks,
as it were producing a temporary warmth;
if it does not proceed from the immediate sensible movings of the spirit of truth,
I much fear the appellation of will-worship is too applicable to it.

I have also had a fear, that a language of old, respecting some of whom it was said,
"`They limited the Holy One of Israel,`" Ps. 78:41.
is applicable to most professing religious societies,
where any particular man or set of men,
assume to themselves the exclusive right of teaching or preaching:
a practice I believe totally repugnant to the gospel dispensation,
and the uniform example and precepts of Christ and his apostles.
For I fully believe that __no human authority, call, qualification, or ordination,
can make a minister of Christ.
That is the prerogative of Christ himself.__
It is absolutely necessary that every individual Christian should be born of the spirit; John 3:5.
and surely it must also be necessary that the ministers of Christ should,
in an especial manner, be so too.
Paul said he was made an apostle,
"`Not of men, neither by man, but by Jesus Christ and God the Father.`" Gal. 1:1.
And, as I before observed,
the dispensation of the gospel being a
"`dispensation of the spirit,`"
the ministers thereof are ministers of the spirit,
and not of the letter: not ministers of the word only, though scripture words themselves;
but of the "`word of eternal life,`" even of the
"`word which was in the beginning, which liveth and abideth forever.`" 1 Pet. 1:23.
That word which is
"`quick and powerful, discerning the thoughts and intents of the heart.`" Heb. 4:12.
Words may have, and no doubt have, their service,
as the spirit brings to remembrance, and giveth utterance;
but to steal the words of Scripture,
see Jer. 23:30-31. and put them in a premeditated form,
however eloquently they may be delivered, I believe is not preaching the gospel.
But I believe, that they who are particularly called, qualified,
and sent by Christ himself, as I believe every true minister is,
will not presume to preach or pray, when, where, or what they please;
but as they are immediately moved and directed by the spirit of Christ,
inwardly revealed; see Gal. 1:16.
who can alone know what is needful to be administered,
and these as they freely receive, they will, agreeably to our Lord`'s command,
_Freely give,_ Matt. 10:8. etc.
"`without any view to temporal interest whatever.`"
And as they are not their own, they cannot dispose of their time or talents,
according to their own wills; but as He who hath called them is pleased to direct.

To conclude: the few observations I have now offered, may perhaps, to unprejudiced minds,
be sufficient to evince the inward spiritual nature of the gospel dispensation;
and that signs and figures, all external ceremonial performances,
are totally abolished from that worship,
which can only be performed in spirit and in truth; John 4:23-24.

They may also evince that the only necessary qualification for true worship,
is the influence and direction of the spirit of truth inwardly revealed:
that this necessary assistance is not confined to time or place,
nor to any particular man or set of men.
For as the apostle declared,
"`The manifestation of the spirit is given to every man, to profit withal,`" 1 Cor. 12:7.
I believe there are no individuals arrived to the years of discretion,
but who are favoured with a sufficient portion thereof, if properly attended to,
to direct them into the paths of true judgment.
The word even the word of eternal life, is nigh to all,
nor need any look to men for instruction; but this same anointing,
if the mind is simply and unreservedly directed to it,
teacheth all things and is truth. 1 John 2:27.
Who is there, who has not felt its secret reproofs for evil,
and its approbation for good?
To this true teacher,
of whose all sufficient aid I have thankfully to acknowledge a degree of experience,
I do earnestly recommend the particular, unwearied, faithful,
attention of every individual.

[.signed-section-signature]
John Spalding

[.signed-section-context-close]
Reading, 30th of the 7th Month, 1794,

[.the-end]
FINIS.
